-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_top_sobel_core_Pipeline_VITIS_LOOP_47_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    total : IN STD_LOGIC_VECTOR (21 downto 0);
    width : IN STD_LOGIC_VECTOR (10 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    linebuf0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf0_ce0 : OUT STD_LOGIC;
    linebuf0_we0 : OUT STD_LOGIC;
    linebuf0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    linebuf1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf1_ce0 : OUT STD_LOGIC;
    linebuf1_we0 : OUT STD_LOGIC;
    linebuf1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty : IN STD_LOGIC_VECTOR (10 downto 0);
    add_ln84 : IN STD_LOGIC_VECTOR (21 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of sobel_top_sobel_core_Pipeline_VITIS_LOOP_47_4 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv22_1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln47_reg_842 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state28_pp0_stage0_iter27_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln47_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal width_cast_fu_264_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal width_cast_reg_829 : STD_LOGIC_VECTOR (21 downto 0);
    signal idx_1_reg_834 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln47_reg_842_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_842_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_846_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_851_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_856_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_343_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal col_reg_861 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_4_reg_866 : STD_LOGIC_VECTOR (10 downto 0);
    signal in_pkt_data_reg_871 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pkt_data_reg_871_pp0_iter28_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pkt_data_reg_871_pp0_iter29_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pkt_data_reg_871_pp0_iter30_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pkt_data_reg_871_pp0_iter31_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln19_fu_387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal linebuf0_addr_reg_885 : STD_LOGIC_VECTOR (10 downto 0);
    signal linebuf0_addr_reg_885_pp0_iter28_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln61_1_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_905 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_905_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_905_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_905_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_905_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_905_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_905_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp55_reg_910 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp55_reg_910_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp55_reg_910_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal reuse_select_fu_428_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select_reg_920 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select_reg_920_pp0_iter30_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select56_fu_461_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select56_reg_927 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_487_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_reg_932 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln64_fu_493_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln64_reg_937 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp3_fu_507_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp3_reg_942 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln68_fu_513_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln68_reg_947 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln62_fu_596_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln62_reg_952 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln67_fu_636_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln67_reg_958 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_5_reg_964 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_969 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln12_fu_661_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln12_reg_974 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln12_1_fu_676_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln12_1_reg_979 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_reg_984 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_condition_exit_pp0_iter31_stage0 : STD_LOGIC;
    signal reuse_addr_reg52_fu_124 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg51_fu_128 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal reuse_addr_reg_fu_132 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_136 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal idx_fu_140 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    signal idx_2_fu_332_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_sig_allocacmp_idx_1 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_0_0_0157277_fu_144 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_0155279_fu_148 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_0153281_fu_152 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_0156278_fu_156 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_0154280_fu_160 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_0152282_fu_164 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal linebuf1_ce0_local : STD_LOGIC;
    signal linebuf1_we0_local : STD_LOGIC;
    signal linebuf0_ce0_local : STD_LOGIC;
    signal linebuf0_we0_local : STD_LOGIC;
    signal grp_fu_343_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p2y_fu_347_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln61_fu_354_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln65_fu_480_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_0_0_0155279_cast_fu_476_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln63_fu_472_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln65_1_fu_483_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_0_0_0152282_cast_fu_503_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_0_0_0156278_cast_fu_499_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_556_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal in_pkt_data_cast_fu_553_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln64_fu_567_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln64_fu_570_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln64_fu_563_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal linebuf0_load_cast_fu_547_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln65_fu_580_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln65_fu_576_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_fu_586_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_600_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln68_fu_607_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal in_pkt_data_cast1_fu_550_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln69_fu_614_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln69_fu_611_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln69_1_fu_620_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_fu_626_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln62_fu_592_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln67_fu_632_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln12_fu_656_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln12_1_fu_671_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln10_fu_667_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln71_fu_682_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mag_fu_686_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal xor_ln61_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln71_fu_712_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln6_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln7_fu_721_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln61_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_fu_725_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_343_ce : STD_LOGIC;
    signal grp_fu_395_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_00001_grp1 : BOOLEAN;
    signal grp_fu_404_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter31_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter32_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter33_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_top_urem_22ns_11ns_22_26_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component sobel_top_icmp_64ns_64ns_1_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        OP_CODE : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component sobel_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_22ns_11ns_22_26_1_U4 : component sobel_top_urem_22ns_11ns_22_26_1
    generic map (
        ID => 1,
        NUM_STAGE => 26,
        din0_WIDTH => 22,
        din1_WIDTH => 11,
        dout_WIDTH => 22)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => idx_1_reg_834,
        din1 => grp_fu_343_p1,
        ce => grp_fu_343_ce,
        dout => grp_fu_343_p2);

    icmp_64ns_64ns_1_2_1_U5 : component sobel_top_icmp_64ns_64ns_1_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        OP_CODE => 0,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reuse_addr_reg52_fu_124,
        din1 => zext_ln19_fu_387_p1,
        ce => grp_fu_395_ce,
        dout => grp_fu_395_p2);

    icmp_64ns_64ns_1_2_1_U6 : component sobel_top_icmp_64ns_64ns_1_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        OP_CODE => 0,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reuse_addr_reg_fu_132,
        din1 => zext_ln19_fu_387_p1,
        ce => grp_fu_404_ce,
        dout => grp_fu_404_p2);

    flow_control_loop_pipe_sequential_init_U : component sobel_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter33_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter31_stage0)) then 
                    ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    idx_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln47_fu_326_p2 = ap_const_lv1_1))) then 
                    idx_fu_140 <= idx_2_fu_332_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    idx_fu_140 <= ap_const_lv22_0;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0152282_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_0152282_fu_164 <= ap_const_lv8_0;
                elsif (((icmp_ln47_reg_842_pp0_iter30_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
                    p_0_0_0152282_fu_164 <= in_pkt_data_reg_871_pp0_iter30_reg;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0153281_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_0153281_fu_152 <= ap_const_lv8_0;
                elsif (((icmp_ln47_reg_842_pp0_iter30_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
                    p_0_0_0153281_fu_152 <= p_0_0_0152282_fu_164;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0154280_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_0154280_fu_160 <= ap_const_lv8_0;
                elsif (((icmp_ln47_reg_842_pp0_iter30_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
                    p_0_0_0154280_fu_160 <= reuse_select_reg_920_pp0_iter30_reg;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0155279_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_0155279_fu_148 <= ap_const_lv8_0;
                elsif (((icmp_ln47_reg_842_pp0_iter30_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
                    p_0_0_0155279_fu_148 <= p_0_0_0154280_fu_160;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0156278_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_0156278_fu_156 <= ap_const_lv8_0;
                elsif (((icmp_ln47_reg_842_pp0_iter30_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
                    p_0_0_0156278_fu_156 <= reuse_select56_fu_461_p3;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0157277_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_0157277_fu_144 <= ap_const_lv8_0;
                elsif (((icmp_ln47_reg_842_pp0_iter30_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
                    p_0_0_0157277_fu_144 <= p_0_0_0156278_fu_156;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg52_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg52_fu_124 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln47_reg_842_pp0_iter26_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
                    reuse_addr_reg52_fu_124 <= zext_ln19_fu_387_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg_fu_132 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln47_reg_842_pp0_iter26_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
                    reuse_addr_reg_fu_132 <= zext_ln19_fu_387_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg51_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg51_fu_128 <= ap_const_lv8_0;
                elsif (((icmp_ln47_reg_842_pp0_iter30_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
                    reuse_reg51_fu_128 <= reuse_select_reg_920_pp0_iter30_reg;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_136 <= ap_const_lv8_0;
                elsif (((icmp_ln47_reg_842_pp0_iter28_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter29 = ap_const_logic_1))) then 
                    reuse_reg_fu_136 <= in_pkt_data_reg_871_pp0_iter28_reg;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln64_reg_937 <= add_ln64_fu_493_p2;
                addr_cmp55_reg_910 <= grp_fu_395_p2;
                addr_cmp55_reg_910_pp0_iter29_reg <= addr_cmp55_reg_910;
                addr_cmp55_reg_910_pp0_iter30_reg <= addr_cmp55_reg_910_pp0_iter29_reg;
                addr_cmp_reg_915 <= grp_fu_404_p2;
                col_reg_861 <= grp_fu_343_p2;
                icmp_ln61_1_reg_905 <= icmp_ln61_1_fu_420_p2;
                icmp_ln61_1_reg_905_pp0_iter28_reg <= icmp_ln61_1_reg_905;
                icmp_ln61_1_reg_905_pp0_iter29_reg <= icmp_ln61_1_reg_905_pp0_iter28_reg;
                icmp_ln61_1_reg_905_pp0_iter30_reg <= icmp_ln61_1_reg_905_pp0_iter29_reg;
                icmp_ln61_1_reg_905_pp0_iter31_reg <= icmp_ln61_1_reg_905_pp0_iter30_reg;
                icmp_ln61_1_reg_905_pp0_iter32_reg <= icmp_ln61_1_reg_905_pp0_iter31_reg;
                icmp_ln61_1_reg_905_pp0_iter33_reg <= icmp_ln61_1_reg_905_pp0_iter32_reg;
                icmp_ln61_reg_846_pp0_iter10_reg <= icmp_ln61_reg_846_pp0_iter9_reg;
                icmp_ln61_reg_846_pp0_iter11_reg <= icmp_ln61_reg_846_pp0_iter10_reg;
                icmp_ln61_reg_846_pp0_iter12_reg <= icmp_ln61_reg_846_pp0_iter11_reg;
                icmp_ln61_reg_846_pp0_iter13_reg <= icmp_ln61_reg_846_pp0_iter12_reg;
                icmp_ln61_reg_846_pp0_iter14_reg <= icmp_ln61_reg_846_pp0_iter13_reg;
                icmp_ln61_reg_846_pp0_iter15_reg <= icmp_ln61_reg_846_pp0_iter14_reg;
                icmp_ln61_reg_846_pp0_iter16_reg <= icmp_ln61_reg_846_pp0_iter15_reg;
                icmp_ln61_reg_846_pp0_iter17_reg <= icmp_ln61_reg_846_pp0_iter16_reg;
                icmp_ln61_reg_846_pp0_iter18_reg <= icmp_ln61_reg_846_pp0_iter17_reg;
                icmp_ln61_reg_846_pp0_iter19_reg <= icmp_ln61_reg_846_pp0_iter18_reg;
                icmp_ln61_reg_846_pp0_iter20_reg <= icmp_ln61_reg_846_pp0_iter19_reg;
                icmp_ln61_reg_846_pp0_iter21_reg <= icmp_ln61_reg_846_pp0_iter20_reg;
                icmp_ln61_reg_846_pp0_iter22_reg <= icmp_ln61_reg_846_pp0_iter21_reg;
                icmp_ln61_reg_846_pp0_iter23_reg <= icmp_ln61_reg_846_pp0_iter22_reg;
                icmp_ln61_reg_846_pp0_iter24_reg <= icmp_ln61_reg_846_pp0_iter23_reg;
                icmp_ln61_reg_846_pp0_iter25_reg <= icmp_ln61_reg_846_pp0_iter24_reg;
                icmp_ln61_reg_846_pp0_iter26_reg <= icmp_ln61_reg_846_pp0_iter25_reg;
                icmp_ln61_reg_846_pp0_iter27_reg <= icmp_ln61_reg_846_pp0_iter26_reg;
                icmp_ln61_reg_846_pp0_iter28_reg <= icmp_ln61_reg_846_pp0_iter27_reg;
                icmp_ln61_reg_846_pp0_iter29_reg <= icmp_ln61_reg_846_pp0_iter28_reg;
                icmp_ln61_reg_846_pp0_iter2_reg <= icmp_ln61_reg_846;
                icmp_ln61_reg_846_pp0_iter30_reg <= icmp_ln61_reg_846_pp0_iter29_reg;
                icmp_ln61_reg_846_pp0_iter31_reg <= icmp_ln61_reg_846_pp0_iter30_reg;
                icmp_ln61_reg_846_pp0_iter32_reg <= icmp_ln61_reg_846_pp0_iter31_reg;
                icmp_ln61_reg_846_pp0_iter33_reg <= icmp_ln61_reg_846_pp0_iter32_reg;
                icmp_ln61_reg_846_pp0_iter3_reg <= icmp_ln61_reg_846_pp0_iter2_reg;
                icmp_ln61_reg_846_pp0_iter4_reg <= icmp_ln61_reg_846_pp0_iter3_reg;
                icmp_ln61_reg_846_pp0_iter5_reg <= icmp_ln61_reg_846_pp0_iter4_reg;
                icmp_ln61_reg_846_pp0_iter6_reg <= icmp_ln61_reg_846_pp0_iter5_reg;
                icmp_ln61_reg_846_pp0_iter7_reg <= icmp_ln61_reg_846_pp0_iter6_reg;
                icmp_ln61_reg_846_pp0_iter8_reg <= icmp_ln61_reg_846_pp0_iter7_reg;
                icmp_ln61_reg_846_pp0_iter9_reg <= icmp_ln61_reg_846_pp0_iter8_reg;
                icmp_ln81_reg_851_pp0_iter10_reg <= icmp_ln81_reg_851_pp0_iter9_reg;
                icmp_ln81_reg_851_pp0_iter11_reg <= icmp_ln81_reg_851_pp0_iter10_reg;
                icmp_ln81_reg_851_pp0_iter12_reg <= icmp_ln81_reg_851_pp0_iter11_reg;
                icmp_ln81_reg_851_pp0_iter13_reg <= icmp_ln81_reg_851_pp0_iter12_reg;
                icmp_ln81_reg_851_pp0_iter14_reg <= icmp_ln81_reg_851_pp0_iter13_reg;
                icmp_ln81_reg_851_pp0_iter15_reg <= icmp_ln81_reg_851_pp0_iter14_reg;
                icmp_ln81_reg_851_pp0_iter16_reg <= icmp_ln81_reg_851_pp0_iter15_reg;
                icmp_ln81_reg_851_pp0_iter17_reg <= icmp_ln81_reg_851_pp0_iter16_reg;
                icmp_ln81_reg_851_pp0_iter18_reg <= icmp_ln81_reg_851_pp0_iter17_reg;
                icmp_ln81_reg_851_pp0_iter19_reg <= icmp_ln81_reg_851_pp0_iter18_reg;
                icmp_ln81_reg_851_pp0_iter20_reg <= icmp_ln81_reg_851_pp0_iter19_reg;
                icmp_ln81_reg_851_pp0_iter21_reg <= icmp_ln81_reg_851_pp0_iter20_reg;
                icmp_ln81_reg_851_pp0_iter22_reg <= icmp_ln81_reg_851_pp0_iter21_reg;
                icmp_ln81_reg_851_pp0_iter23_reg <= icmp_ln81_reg_851_pp0_iter22_reg;
                icmp_ln81_reg_851_pp0_iter24_reg <= icmp_ln81_reg_851_pp0_iter23_reg;
                icmp_ln81_reg_851_pp0_iter25_reg <= icmp_ln81_reg_851_pp0_iter24_reg;
                icmp_ln81_reg_851_pp0_iter26_reg <= icmp_ln81_reg_851_pp0_iter25_reg;
                icmp_ln81_reg_851_pp0_iter27_reg <= icmp_ln81_reg_851_pp0_iter26_reg;
                icmp_ln81_reg_851_pp0_iter28_reg <= icmp_ln81_reg_851_pp0_iter27_reg;
                icmp_ln81_reg_851_pp0_iter29_reg <= icmp_ln81_reg_851_pp0_iter28_reg;
                icmp_ln81_reg_851_pp0_iter2_reg <= icmp_ln81_reg_851;
                icmp_ln81_reg_851_pp0_iter30_reg <= icmp_ln81_reg_851_pp0_iter29_reg;
                icmp_ln81_reg_851_pp0_iter31_reg <= icmp_ln81_reg_851_pp0_iter30_reg;
                icmp_ln81_reg_851_pp0_iter32_reg <= icmp_ln81_reg_851_pp0_iter31_reg;
                icmp_ln81_reg_851_pp0_iter33_reg <= icmp_ln81_reg_851_pp0_iter32_reg;
                icmp_ln81_reg_851_pp0_iter3_reg <= icmp_ln81_reg_851_pp0_iter2_reg;
                icmp_ln81_reg_851_pp0_iter4_reg <= icmp_ln81_reg_851_pp0_iter3_reg;
                icmp_ln81_reg_851_pp0_iter5_reg <= icmp_ln81_reg_851_pp0_iter4_reg;
                icmp_ln81_reg_851_pp0_iter6_reg <= icmp_ln81_reg_851_pp0_iter5_reg;
                icmp_ln81_reg_851_pp0_iter7_reg <= icmp_ln81_reg_851_pp0_iter6_reg;
                icmp_ln81_reg_851_pp0_iter8_reg <= icmp_ln81_reg_851_pp0_iter7_reg;
                icmp_ln81_reg_851_pp0_iter9_reg <= icmp_ln81_reg_851_pp0_iter8_reg;
                icmp_ln84_reg_856_pp0_iter10_reg <= icmp_ln84_reg_856_pp0_iter9_reg;
                icmp_ln84_reg_856_pp0_iter11_reg <= icmp_ln84_reg_856_pp0_iter10_reg;
                icmp_ln84_reg_856_pp0_iter12_reg <= icmp_ln84_reg_856_pp0_iter11_reg;
                icmp_ln84_reg_856_pp0_iter13_reg <= icmp_ln84_reg_856_pp0_iter12_reg;
                icmp_ln84_reg_856_pp0_iter14_reg <= icmp_ln84_reg_856_pp0_iter13_reg;
                icmp_ln84_reg_856_pp0_iter15_reg <= icmp_ln84_reg_856_pp0_iter14_reg;
                icmp_ln84_reg_856_pp0_iter16_reg <= icmp_ln84_reg_856_pp0_iter15_reg;
                icmp_ln84_reg_856_pp0_iter17_reg <= icmp_ln84_reg_856_pp0_iter16_reg;
                icmp_ln84_reg_856_pp0_iter18_reg <= icmp_ln84_reg_856_pp0_iter17_reg;
                icmp_ln84_reg_856_pp0_iter19_reg <= icmp_ln84_reg_856_pp0_iter18_reg;
                icmp_ln84_reg_856_pp0_iter20_reg <= icmp_ln84_reg_856_pp0_iter19_reg;
                icmp_ln84_reg_856_pp0_iter21_reg <= icmp_ln84_reg_856_pp0_iter20_reg;
                icmp_ln84_reg_856_pp0_iter22_reg <= icmp_ln84_reg_856_pp0_iter21_reg;
                icmp_ln84_reg_856_pp0_iter23_reg <= icmp_ln84_reg_856_pp0_iter22_reg;
                icmp_ln84_reg_856_pp0_iter24_reg <= icmp_ln84_reg_856_pp0_iter23_reg;
                icmp_ln84_reg_856_pp0_iter25_reg <= icmp_ln84_reg_856_pp0_iter24_reg;
                icmp_ln84_reg_856_pp0_iter26_reg <= icmp_ln84_reg_856_pp0_iter25_reg;
                icmp_ln84_reg_856_pp0_iter27_reg <= icmp_ln84_reg_856_pp0_iter26_reg;
                icmp_ln84_reg_856_pp0_iter28_reg <= icmp_ln84_reg_856_pp0_iter27_reg;
                icmp_ln84_reg_856_pp0_iter29_reg <= icmp_ln84_reg_856_pp0_iter28_reg;
                icmp_ln84_reg_856_pp0_iter2_reg <= icmp_ln84_reg_856;
                icmp_ln84_reg_856_pp0_iter30_reg <= icmp_ln84_reg_856_pp0_iter29_reg;
                icmp_ln84_reg_856_pp0_iter31_reg <= icmp_ln84_reg_856_pp0_iter30_reg;
                icmp_ln84_reg_856_pp0_iter32_reg <= icmp_ln84_reg_856_pp0_iter31_reg;
                icmp_ln84_reg_856_pp0_iter33_reg <= icmp_ln84_reg_856_pp0_iter32_reg;
                icmp_ln84_reg_856_pp0_iter3_reg <= icmp_ln84_reg_856_pp0_iter2_reg;
                icmp_ln84_reg_856_pp0_iter4_reg <= icmp_ln84_reg_856_pp0_iter3_reg;
                icmp_ln84_reg_856_pp0_iter5_reg <= icmp_ln84_reg_856_pp0_iter4_reg;
                icmp_ln84_reg_856_pp0_iter6_reg <= icmp_ln84_reg_856_pp0_iter5_reg;
                icmp_ln84_reg_856_pp0_iter7_reg <= icmp_ln84_reg_856_pp0_iter6_reg;
                icmp_ln84_reg_856_pp0_iter8_reg <= icmp_ln84_reg_856_pp0_iter7_reg;
                icmp_ln84_reg_856_pp0_iter9_reg <= icmp_ln84_reg_856_pp0_iter8_reg;
                in_pkt_data_reg_871 <= in_stream_TDATA;
                in_pkt_data_reg_871_pp0_iter28_reg <= in_pkt_data_reg_871;
                in_pkt_data_reg_871_pp0_iter29_reg <= in_pkt_data_reg_871_pp0_iter28_reg;
                in_pkt_data_reg_871_pp0_iter30_reg <= in_pkt_data_reg_871_pp0_iter29_reg;
                in_pkt_data_reg_871_pp0_iter31_reg <= in_pkt_data_reg_871_pp0_iter30_reg;
                linebuf0_addr_reg_885 <= zext_ln19_fu_387_p1(11 - 1 downto 0);
                linebuf0_addr_reg_885_pp0_iter28_reg <= linebuf0_addr_reg_885;
                reuse_select56_reg_927 <= reuse_select56_fu_461_p3;
                reuse_select_reg_920 <= reuse_select_fu_428_p3;
                reuse_select_reg_920_pp0_iter30_reg <= reuse_select_reg_920;
                select_ln12_1_reg_979 <= select_ln12_1_fu_676_p3;
                select_ln12_reg_974 <= select_ln12_fu_661_p3;
                sub_ln68_reg_947 <= sub_ln68_fu_513_p2;
                tmp3_reg_942 <= tmp3_fu_507_p2;
                tmp_4_reg_866 <= grp_fu_343_p2(11 downto 1);
                tmp_5_reg_964 <= sext_ln62_fu_592_p1(31 downto 31);
                tmp_6_reg_969 <= sext_ln67_fu_632_p1(31 downto 31);
                tmp_7_reg_984 <= mag_fu_686_p2(10 downto 8);
                tmp_reg_932 <= tmp_fu_487_p2;
                trunc_ln62_reg_952 <= trunc_ln62_fu_596_p1;
                trunc_ln67_reg_958 <= trunc_ln67_fu_636_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
                ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
                ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln47_reg_842_pp0_iter10_reg <= icmp_ln47_reg_842_pp0_iter9_reg;
                icmp_ln47_reg_842_pp0_iter11_reg <= icmp_ln47_reg_842_pp0_iter10_reg;
                icmp_ln47_reg_842_pp0_iter12_reg <= icmp_ln47_reg_842_pp0_iter11_reg;
                icmp_ln47_reg_842_pp0_iter13_reg <= icmp_ln47_reg_842_pp0_iter12_reg;
                icmp_ln47_reg_842_pp0_iter14_reg <= icmp_ln47_reg_842_pp0_iter13_reg;
                icmp_ln47_reg_842_pp0_iter15_reg <= icmp_ln47_reg_842_pp0_iter14_reg;
                icmp_ln47_reg_842_pp0_iter16_reg <= icmp_ln47_reg_842_pp0_iter15_reg;
                icmp_ln47_reg_842_pp0_iter17_reg <= icmp_ln47_reg_842_pp0_iter16_reg;
                icmp_ln47_reg_842_pp0_iter18_reg <= icmp_ln47_reg_842_pp0_iter17_reg;
                icmp_ln47_reg_842_pp0_iter19_reg <= icmp_ln47_reg_842_pp0_iter18_reg;
                icmp_ln47_reg_842_pp0_iter20_reg <= icmp_ln47_reg_842_pp0_iter19_reg;
                icmp_ln47_reg_842_pp0_iter21_reg <= icmp_ln47_reg_842_pp0_iter20_reg;
                icmp_ln47_reg_842_pp0_iter22_reg <= icmp_ln47_reg_842_pp0_iter21_reg;
                icmp_ln47_reg_842_pp0_iter23_reg <= icmp_ln47_reg_842_pp0_iter22_reg;
                icmp_ln47_reg_842_pp0_iter24_reg <= icmp_ln47_reg_842_pp0_iter23_reg;
                icmp_ln47_reg_842_pp0_iter25_reg <= icmp_ln47_reg_842_pp0_iter24_reg;
                icmp_ln47_reg_842_pp0_iter26_reg <= icmp_ln47_reg_842_pp0_iter25_reg;
                icmp_ln47_reg_842_pp0_iter27_reg <= icmp_ln47_reg_842_pp0_iter26_reg;
                icmp_ln47_reg_842_pp0_iter28_reg <= icmp_ln47_reg_842_pp0_iter27_reg;
                icmp_ln47_reg_842_pp0_iter29_reg <= icmp_ln47_reg_842_pp0_iter28_reg;
                icmp_ln47_reg_842_pp0_iter2_reg <= icmp_ln47_reg_842_pp0_iter1_reg;
                icmp_ln47_reg_842_pp0_iter30_reg <= icmp_ln47_reg_842_pp0_iter29_reg;
                icmp_ln47_reg_842_pp0_iter3_reg <= icmp_ln47_reg_842_pp0_iter2_reg;
                icmp_ln47_reg_842_pp0_iter4_reg <= icmp_ln47_reg_842_pp0_iter3_reg;
                icmp_ln47_reg_842_pp0_iter5_reg <= icmp_ln47_reg_842_pp0_iter4_reg;
                icmp_ln47_reg_842_pp0_iter6_reg <= icmp_ln47_reg_842_pp0_iter5_reg;
                icmp_ln47_reg_842_pp0_iter7_reg <= icmp_ln47_reg_842_pp0_iter6_reg;
                icmp_ln47_reg_842_pp0_iter8_reg <= icmp_ln47_reg_842_pp0_iter7_reg;
                icmp_ln47_reg_842_pp0_iter9_reg <= icmp_ln47_reg_842_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln47_reg_842 <= icmp_ln47_fu_326_p2;
                icmp_ln47_reg_842_pp0_iter1_reg <= icmp_ln47_reg_842;
                idx_1_reg_834 <= ap_sig_allocacmp_idx_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                icmp_ln61_reg_846 <= icmp_ln61_fu_358_p2;
                icmp_ln81_reg_851 <= icmp_ln81_fu_363_p2;
                icmp_ln84_reg_856 <= icmp_ln84_fu_368_p2;
                    width_cast_reg_829(10 downto 0) <= width_cast_fu_264_p1(10 downto 0);
            end if;
        end if;
    end process;
    width_cast_reg_829(21 downto 11) <= "00000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln64_fu_493_p2 <= std_logic_vector(unsigned(zext_ln63_fu_472_p1) + unsigned(zext_ln65_1_fu_483_p1));
    add_ln65_fu_580_p2 <= std_logic_vector(signed(sext_ln64_fu_563_p1) + signed(linebuf0_load_cast_fu_547_p1));
    add_ln69_1_fu_620_p2 <= std_logic_vector(unsigned(add_ln69_fu_614_p2) + unsigned(sext_ln69_fu_611_p1));
    add_ln69_fu_614_p2 <= std_logic_vector(signed(sext_ln68_fu_607_p1) + signed(in_pkt_data_cast1_fu_550_p1));
    add_ln71_fu_712_p2 <= std_logic_vector(unsigned(select_ln12_reg_974) + unsigned(select_ln12_1_reg_979));
    and_ln61_fu_707_p2 <= (xor_ln61_fu_702_p2 and icmp_ln61_1_reg_905_pp0_iter33_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_00001_grp1_assign_proc : process(ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter34, out_stream_TREADY, ap_block_state28_pp0_stage0_iter27_grp1)
    begin
                ap_block_pp0_stage0_00001_grp1 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state28_pp0_stage0_iter27_grp1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter34, out_stream_TREADY, ap_block_state28_pp0_stage0_iter27_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state28_pp0_stage0_iter27_grp1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter34, out_stream_TREADY, ap_block_state28_pp0_stage0_iter27_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state28_pp0_stage0_iter27_grp1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter34, out_stream_TREADY, ap_block_state28_pp0_stage0_iter27_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state28_pp0_stage0_iter27_grp1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter34, out_stream_TREADY, ap_block_state28_pp0_stage0_iter27_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state28_pp0_stage0_iter27_grp1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state28_pp0_stage0_iter27_grp1_assign_proc : process(in_stream_TVALID, icmp_ln47_reg_842_pp0_iter26_reg)
    begin
                ap_block_state28_pp0_stage0_iter27_grp1 <= ((icmp_ln47_reg_842_pp0_iter26_reg = ap_const_lv1_1) and (in_stream_TVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln47_fu_326_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln47_fu_326_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter31_stage0_assign_proc : process(ap_enable_reg_pp0_iter31, ap_block_pp0_stage0_subdone, icmp_ln47_reg_842_pp0_iter30_reg)
    begin
        if (((icmp_ln47_reg_842_pp0_iter30_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter31_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter31_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter33_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter33_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = 
    ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_idx_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, idx_fu_140, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_idx_1 <= ap_const_lv22_0;
        else 
            ap_sig_allocacmp_idx_1 <= idx_fu_140;
        end if; 
    end process;


    grp_fu_343_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_343_ce <= ap_const_logic_1;
        else 
            grp_fu_343_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_343_p1 <= width_cast_reg_829(11 - 1 downto 0);

    grp_fu_395_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_395_ce <= ap_const_logic_1;
        else 
            grp_fu_395_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_404_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_404_ce <= ap_const_logic_1;
        else 
            grp_fu_404_ce <= ap_const_logic_0;
        end if; 
    end process;

    gx_fu_586_p2 <= std_logic_vector(unsigned(add_ln65_fu_580_p2) + unsigned(sext_ln65_fu_576_p1));
    gy_fu_626_p2 <= std_logic_vector(unsigned(add_ln69_1_fu_620_p2) - unsigned(linebuf0_load_cast_fu_547_p1));
    icmp_ln47_fu_326_p2 <= "1" when (unsigned(ap_sig_allocacmp_idx_1) < unsigned(total)) else "0";
    icmp_ln61_1_fu_420_p2 <= "1" when (signed(tmp_4_reg_866) > signed(ap_const_lv11_0)) else "0";
    icmp_ln61_fu_358_p2 <= "1" when (unsigned(idx_1_reg_834) < unsigned(zext_ln61_fu_354_p1)) else "0";
    icmp_ln6_fu_716_p2 <= "0" when (tmp_7_reg_984 = ap_const_lv3_0) else "1";
    icmp_ln81_fu_363_p2 <= "1" when (idx_1_reg_834 = ap_const_lv22_0) else "0";
    icmp_ln84_fu_368_p2 <= "1" when (idx_1_reg_834 = add_ln84) else "0";
    idx_2_fu_332_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_idx_1) + unsigned(ap_const_lv22_1));
    in_pkt_data_cast1_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pkt_data_reg_871_pp0_iter31_reg),11));
    in_pkt_data_cast_fu_553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pkt_data_reg_871_pp0_iter31_reg),10));

    in_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter27, in_stream_TVALID, icmp_ln47_reg_842_pp0_iter26_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln47_reg_842_pp0_iter26_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_enable_reg_pp0_iter27, icmp_ln47_reg_842_pp0_iter26_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln47_reg_842_pp0_iter26_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    linebuf0_address0 <= linebuf0_addr_reg_885_pp0_iter28_reg;
    linebuf0_ce0 <= linebuf0_ce0_local;

    linebuf0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_block_pp0_stage0_11001_grp1, icmp_ln47_reg_842_pp0_iter28_reg, addr_cmp55_reg_910)
    begin
        if ((((icmp_ln47_reg_842_pp0_iter28_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = addr_cmp55_reg_910) and (ap_enable_reg_pp0_iter29 = ap_const_logic_1)) or ((icmp_ln47_reg_842_pp0_iter28_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter29 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter30 = ap_const_logic_1)))) then 
            linebuf0_ce0_local <= ap_const_logic_1;
        else 
            linebuf0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf0_d0 <= reuse_select_fu_428_p3;
    linebuf0_load_cast_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select56_reg_927),11));
    linebuf0_we0 <= linebuf0_we0_local;

    linebuf0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter29, ap_block_pp0_stage0_11001_grp1, icmp_ln47_reg_842_pp0_iter28_reg)
    begin
        if (((icmp_ln47_reg_842_pp0_iter28_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter29 = ap_const_logic_1))) then 
            linebuf0_we0_local <= ap_const_logic_1;
        else 
            linebuf0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf1_address0 <= zext_ln19_fu_387_p1(11 - 1 downto 0);
    linebuf1_ce0 <= linebuf1_ce0_local;

    linebuf1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, icmp_ln47_reg_842_pp0_iter26_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln47_reg_842_pp0_iter26_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)))) then 
            linebuf1_ce0_local <= ap_const_logic_1;
        else 
            linebuf1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf1_d0 <= in_stream_TDATA;
    linebuf1_we0 <= linebuf1_we0_local;

    linebuf1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter27, icmp_ln47_reg_842_pp0_iter26_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln47_reg_842_pp0_iter26_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            linebuf1_we0_local <= ap_const_logic_1;
        else 
            linebuf1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    mag_fu_686_p2 <= std_logic_vector(unsigned(zext_ln10_fu_667_p1) + unsigned(zext_ln71_fu_682_p1));
    out_pix_fu_725_p3 <= 
        ap_const_lv8_FF when (icmp_ln6_fu_716_p2(0) = '1') else 
        trunc_ln7_fu_721_p1;
    out_stream_TDATA <= 
        out_pix_fu_725_p3 when (and_ln61_fu_707_p2(0) = '1') else 
        ap_const_lv8_0;

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter34, out_stream_TREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDEST <= ap_const_lv1_0;
    out_stream_TID <= ap_const_lv1_0;
    out_stream_TKEEP <= ap_const_lv1_1;
    out_stream_TLAST <= icmp_ln84_reg_856_pp0_iter33_reg;
    out_stream_TSTRB <= ap_const_lv1_1;
    out_stream_TUSER <= icmp_ln81_reg_851_pp0_iter33_reg;

    out_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    p2y_fu_347_p3 <= (empty & ap_const_lv1_0);
    p_0_0_0152282_cast_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0152282_fu_164),9));
    p_0_0_0155279_cast_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0155279_fu_148),9));
    p_0_0_0156278_cast_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0156278_fu_156),9));
    reuse_select56_fu_461_p3 <= 
        reuse_reg51_fu_128 when (addr_cmp55_reg_910_pp0_iter30_reg(0) = '1') else 
        linebuf0_q0;
    reuse_select_fu_428_p3 <= 
        reuse_reg_fu_136 when (addr_cmp_reg_915(0) = '1') else 
        linebuf1_q0;
    select_ln12_1_fu_676_p3 <= 
        sub_ln12_1_fu_671_p2 when (tmp_6_reg_969(0) = '1') else 
        trunc_ln67_reg_958;
    select_ln12_fu_661_p3 <= 
        sub_ln12_fu_656_p2 when (tmp_5_reg_964(0) = '1') else 
        trunc_ln62_reg_952;
        sext_ln62_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gx_fu_586_p2),32));

        sext_ln64_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_556_p3),11));

        sext_ln65_fu_576_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln64_fu_570_p2),11));

        sext_ln67_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gy_fu_626_p2),32));

        sext_ln68_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_600_p3),11));

        sext_ln69_fu_611_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln68_reg_947),11));

    sub_ln12_1_fu_671_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(trunc_ln67_reg_958));
    sub_ln12_fu_656_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(trunc_ln62_reg_952));
    sub_ln64_fu_570_p2 <= std_logic_vector(unsigned(in_pkt_data_cast_fu_553_p1) - unsigned(zext_ln64_fu_567_p1));
    sub_ln68_fu_513_p2 <= std_logic_vector(unsigned(zext_ln65_1_fu_483_p1) - unsigned(zext_ln63_fu_472_p1));
    tmp3_fu_507_p2 <= std_logic_vector(unsigned(p_0_0_0152282_cast_fu_503_p1) - unsigned(p_0_0_0156278_cast_fu_499_p1));
    tmp_1_fu_556_p3 <= (tmp_reg_932 & ap_const_lv1_0);
    tmp_2_fu_600_p3 <= (tmp3_reg_942 & ap_const_lv1_0);
    tmp_fu_487_p2 <= std_logic_vector(unsigned(zext_ln65_fu_480_p1) - unsigned(p_0_0_0155279_cast_fu_476_p1));
    trunc_ln62_fu_596_p1 <= gx_fu_586_p2(10 - 1 downto 0);
    trunc_ln67_fu_636_p1 <= gy_fu_626_p2(10 - 1 downto 0);
    trunc_ln7_fu_721_p1 <= add_ln71_fu_712_p2(8 - 1 downto 0);
    width_cast_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),22));
    xor_ln61_fu_702_p2 <= (icmp_ln61_reg_846_pp0_iter33_reg xor ap_const_lv1_1);
    zext_ln10_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln12_fu_661_p3),11));
    zext_ln19_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_reg_861),64));
    zext_ln61_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p2y_fu_347_p3),22));
    zext_ln63_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0157277_fu_144),9));
    zext_ln64_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_reg_937),10));
    zext_ln65_1_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0153281_fu_152),9));
    zext_ln65_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select_reg_920_pp0_iter30_reg),9));
    zext_ln71_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln12_1_fu_676_p3),11));
end behav;
