// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module sobel_top_sobel_core_Pipeline_row_loop_col_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        out_stream_TREADY,
        width,
        mul_ln95,
        zext_ln53_1,
        add_ln95,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        linebuf0_address0,
        linebuf0_ce0,
        linebuf0_q0,
        linebuf0_address1,
        linebuf0_ce1,
        linebuf0_we1,
        linebuf0_d1,
        linebuf1_address1,
        linebuf1_ce1,
        linebuf1_we1,
        linebuf1_d1,
        linebuf1_q1,
        add_ln51,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [10:0] width;
input  [21:0] mul_ln95;
input  [10:0] zext_ln53_1;
input  [10:0] add_ln95;
input  [7:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [10:0] linebuf0_address0;
output   linebuf0_ce0;
input  [7:0] linebuf0_q0;
output  [10:0] linebuf0_address1;
output   linebuf0_ce1;
output   linebuf0_we1;
output  [7:0] linebuf0_d1;
output  [10:0] linebuf1_address1;
output   linebuf1_ce1;
output   linebuf1_we1;
output  [7:0] linebuf1_d1;
input  [7:0] linebuf1_q1;
input  [10:0] add_ln51;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;

reg ap_idle;
reg in_stream_TREADY;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln51_reg_1026;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln51_fu_377_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [21:0] zext_ln53_1_cast_fu_295_p1;
reg   [21:0] zext_ln53_1_cast_reg_1021;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln51_reg_1026_pp0_iter1_reg;
reg   [0:0] icmp_ln51_reg_1026_pp0_iter2_reg;
reg   [0:0] icmp_ln51_reg_1026_pp0_iter3_reg;
reg   [0:0] icmp_ln51_reg_1026_pp0_iter4_reg;
wire   [0:0] icmp_ln53_fu_397_p2;
reg   [0:0] icmp_ln53_reg_1030;
wire   [21:0] add_ln53_fu_416_p2;
reg   [21:0] add_ln53_reg_1035;
wire   [0:0] icmp_ln64_fu_453_p2;
reg   [0:0] icmp_ln64_reg_1040;
reg   [0:0] icmp_ln64_reg_1040_pp0_iter2_reg;
reg   [0:0] icmp_ln64_reg_1040_pp0_iter3_reg;
reg   [0:0] icmp_ln64_reg_1040_pp0_iter4_reg;
reg   [0:0] icmp_ln64_reg_1040_pp0_iter5_reg;
reg   [0:0] icmp_ln64_reg_1040_pp0_iter6_reg;
reg   [7:0] in_pkt_data_reg_1045;
reg   [7:0] in_pkt_data_reg_1045_pp0_iter2_reg;
reg   [7:0] in_pkt_data_reg_1045_pp0_iter3_reg;
reg   [7:0] in_pkt_data_reg_1045_pp0_iter4_reg;
wire   [63:0] zext_ln10_fu_469_p1;
reg   [63:0] zext_ln10_reg_1052;
wire   [0:0] icmp_ln64_1_fu_484_p2;
reg   [0:0] icmp_ln64_1_reg_1066;
reg   [0:0] icmp_ln64_1_reg_1066_pp0_iter2_reg;
reg   [0:0] icmp_ln64_1_reg_1066_pp0_iter3_reg;
reg   [0:0] icmp_ln64_1_reg_1066_pp0_iter4_reg;
reg   [0:0] icmp_ln64_1_reg_1066_pp0_iter5_reg;
reg   [0:0] icmp_ln64_1_reg_1066_pp0_iter6_reg;
wire   [0:0] and_ln95_fu_495_p2;
reg   [0:0] and_ln95_reg_1071;
reg   [0:0] and_ln95_reg_1071_pp0_iter2_reg;
reg   [0:0] and_ln95_reg_1071_pp0_iter3_reg;
reg   [0:0] and_ln95_reg_1071_pp0_iter4_reg;
reg   [0:0] and_ln95_reg_1071_pp0_iter5_reg;
reg   [0:0] and_ln95_reg_1071_pp0_iter6_reg;
reg   [10:0] linebuf0_addr_reg_1076;
wire   [0:0] addr_cmp31_fu_534_p2;
reg   [0:0] addr_cmp31_reg_1082;
wire   [7:0] p12_fu_550_p3;
reg   [7:0] p12_reg_1087;
reg   [7:0] p12_reg_1087_pp0_iter3_reg;
reg   [7:0] p12_reg_1087_pp0_iter4_reg;
wire   [0:0] icmp_ln92_fu_570_p2;
reg   [0:0] icmp_ln92_reg_1095;
reg   [0:0] icmp_ln92_reg_1095_pp0_iter3_reg;
reg   [0:0] icmp_ln92_reg_1095_pp0_iter4_reg;
reg   [0:0] icmp_ln92_reg_1095_pp0_iter5_reg;
reg   [0:0] icmp_ln92_reg_1095_pp0_iter6_reg;
wire   [7:0] reuse_select32_fu_590_p3;
reg   [7:0] reuse_select32_reg_1100;
reg   [7:0] reuse_select32_reg_1100_pp0_iter4_reg;
wire   [8:0] add_ln76_fu_629_p2;
reg   [8:0] add_ln76_reg_1107;
wire   [10:0] sub_ln81_fu_675_p2;
reg   [10:0] sub_ln81_reg_1112;
wire   [9:0] trunc_ln78_fu_772_p1;
reg   [9:0] trunc_ln78_reg_1117;
wire   [9:0] trunc_ln82_fu_787_p1;
reg   [9:0] trunc_ln82_reg_1123;
reg   [0:0] tmp_2_reg_1129;
reg   [0:0] tmp_3_reg_1134;
wire   [7:0] add_ln10_fu_854_p2;
reg   [7:0] add_ln10_reg_1139;
wire   [0:0] icmp_ln10_fu_876_p2;
reg   [0:0] icmp_ln10_reg_1144;
reg    ap_condition_exit_pp0_iter5_stage0;
reg   [63:0] reuse_addr_reg28_fu_124;
wire    ap_loop_init;
reg   [7:0] reuse_reg27_fu_128;
reg   [63:0] reuse_addr_reg_fu_132;
reg   [7:0] reuse_reg_fu_136;
reg   [21:0] idx_1_fu_140;
wire   [21:0] idx_3_fu_576_p2;
reg   [10:0] col_fu_144;
wire   [10:0] col_4_fu_501_p2;
reg   [7:0] p_0_0_08371182_fu_148;
reg   [7:0] p10_fu_152;
reg   [7:0] p_0_0_08331186_fu_156;
reg   [21:0] idx_fu_160;
wire   [21:0] select_ln51_3_fu_435_p3;
reg   [10:0] row_fu_164;
wire   [10:0] select_ln51_2_fu_427_p3;
reg   [21:0] indvar_flatten_fu_168;
wire   [21:0] add_ln51_1_fu_383_p2;
reg   [21:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg   [7:0] p01_fu_172;
reg   [7:0] p_0_0_08341185_fu_176;
reg   [7:0] p21_fu_180;
reg    ap_block_pp0_stage0_01001_grp1;
reg    linebuf1_ce1_local;
reg    linebuf1_we1_local;
reg    linebuf0_ce0_local;
reg    linebuf0_we1_local;
reg    linebuf0_ce1_local;
wire   [10:0] add_ln51_2_fu_421_p2;
wire   [9:0] tmp_fu_443_p4;
wire   [10:0] select_ln51_fu_408_p3;
wire   [9:0] tmp_1_fu_474_p4;
wire   [0:0] icmp_ln95_fu_459_p2;
wire   [0:0] icmp_ln95_1_fu_490_p2;
wire   [0:0] addr_cmp_fu_545_p2;
wire   [21:0] select_ln51_1_fu_525_p3;
wire   [8:0] zext_ln77_1_fu_625_p1;
wire   [8:0] zext_ln76_1_fu_617_p1;
wire   [8:0] shl_ln2_fu_635_p3;
wire   [8:0] shl_ln3_fu_647_p3;
wire   [9:0] zext_ln81_fu_655_p1;
wire   [9:0] zext_ln77_fu_621_p1;
wire   [9:0] add_ln80_fu_659_p2;
wire   [10:0] zext_ln80_2_fu_665_p1;
wire   [10:0] zext_ln76_fu_613_p1;
wire   [10:0] gy_top_fu_669_p2;
wire   [10:0] zext_ln80_1_fu_643_p1;
wire   [8:0] shl_ln_fu_705_p3;
wire   [8:0] shl_ln1_fu_717_p3;
wire   [9:0] zext_ln76_3_fu_737_p1;
wire   [9:0] zext_ln80_fu_713_p1;
wire   [9:0] add_ln76_1_fu_740_p2;
wire   [10:0] zext_ln76_2_fu_734_p1;
wire   [10:0] zext_ln77_5_fu_746_p1;
wire   [9:0] zext_ln77_2_fu_724_p1;
wire   [9:0] zext_ln77_4_fu_731_p1;
wire   [9:0] add_ln78_fu_756_p2;
wire   [10:0] zext_ln78_fu_762_p1;
wire   [10:0] sub_ln77_fu_750_p2;
wire   [10:0] gx_fu_766_p2;
wire   [10:0] gy_bot_fu_776_p2;
wire   [10:0] zext_ln77_3_fu_728_p1;
wire   [10:0] gy_fu_781_p2;
wire   [9:0] sub_ln5_fu_816_p2;
wire   [9:0] x_1_fu_821_p3;
wire   [9:0] sub_ln5_1_fu_831_p2;
wire   [9:0] select_ln5_fu_836_p3;
wire   [7:0] trunc_ln5_fu_827_p1;
wire   [7:0] trunc_ln84_fu_842_p1;
wire   [10:0] zext_ln84_fu_846_p1;
wire   [10:0] zext_ln84_1_fu_850_p1;
wire   [10:0] mag_fu_860_p2;
wire   [2:0] tmp_4_fu_866_p4;
wire   [0:0] and_ln64_fu_882_p2;
wire   [7:0] out_pix_fu_886_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 reuse_addr_reg28_fu_124 = 64'd0;
#0 reuse_reg27_fu_128 = 8'd0;
#0 reuse_addr_reg_fu_132 = 64'd0;
#0 reuse_reg_fu_136 = 8'd0;
#0 idx_1_fu_140 = 22'd0;
#0 col_fu_144 = 11'd0;
#0 p_0_0_08371182_fu_148 = 8'd0;
#0 p10_fu_152 = 8'd0;
#0 p_0_0_08331186_fu_156 = 8'd0;
#0 idx_fu_160 = 22'd0;
#0 row_fu_164 = 11'd0;
#0 indvar_flatten_fu_168 = 22'd0;
#0 p01_fu_172 = 8'd0;
#0 p_0_0_08341185_fu_176 = 8'd0;
#0 p21_fu_180 = 8'd0;
#0 ap_done_reg = 1'b0;
end

sobel_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter5_stage0)) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            col_fu_144 <= 11'd0;
        end else if (((icmp_ln51_reg_1026 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            col_fu_144 <= col_4_fu_501_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            idx_1_fu_140 <= 22'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter1_reg == 1'd0))) begin
            idx_1_fu_140 <= idx_3_fu_576_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_fu_160 <= 22'd0;
        end else if (((icmp_ln51_reg_1026 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            idx_fu_160 <= select_ln51_3_fu_435_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln51_fu_377_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_168 <= add_ln51_1_fu_383_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_168 <= 22'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p01_fu_172 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter3_reg == 1'd0))) begin
            p01_fu_172 <= reuse_select32_reg_1100;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p10_fu_152 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter4_reg == 1'd0))) begin
            p10_fu_152 <= p_0_0_08341185_fu_176;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p21_fu_180 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter3_reg == 1'd0))) begin
            p21_fu_180 <= in_pkt_data_reg_1045_pp0_iter3_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_08331186_fu_156 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter3_reg == 1'd0))) begin
            p_0_0_08331186_fu_156 <= p21_fu_180;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_08341185_fu_176 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter4_reg == 1'd0))) begin
            p_0_0_08341185_fu_176 <= p12_reg_1087_pp0_iter4_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_08371182_fu_148 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter3_reg == 1'd0))) begin
            p_0_0_08371182_fu_148 <= p01_fu_172;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg28_fu_124 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter1_reg == 1'd0))) begin
            reuse_addr_reg28_fu_124 <= zext_ln10_reg_1052;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg_fu_132 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter1_reg == 1'd0))) begin
            reuse_addr_reg_fu_132 <= zext_ln10_reg_1052;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg27_fu_128 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter2_reg == 1'd0))) begin
            reuse_reg27_fu_128 <= p12_reg_1087;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_136 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter1_reg == 1'd0))) begin
            reuse_reg_fu_136 <= in_pkt_data_reg_1045;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            row_fu_164 <= 11'd0;
        end else if (((icmp_ln51_reg_1026 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            row_fu_164 <= select_ln51_2_fu_427_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln10_reg_1139 <= add_ln10_fu_854_p2;
        add_ln76_reg_1107 <= add_ln76_fu_629_p2;
        addr_cmp31_reg_1082 <= addr_cmp31_fu_534_p2;
        and_ln95_reg_1071_pp0_iter2_reg <= and_ln95_reg_1071;
        and_ln95_reg_1071_pp0_iter3_reg <= and_ln95_reg_1071_pp0_iter2_reg;
        and_ln95_reg_1071_pp0_iter4_reg <= and_ln95_reg_1071_pp0_iter3_reg;
        and_ln95_reg_1071_pp0_iter5_reg <= and_ln95_reg_1071_pp0_iter4_reg;
        and_ln95_reg_1071_pp0_iter6_reg <= and_ln95_reg_1071_pp0_iter5_reg;
        icmp_ln10_reg_1144 <= icmp_ln10_fu_876_p2;
        icmp_ln64_1_reg_1066_pp0_iter2_reg <= icmp_ln64_1_reg_1066;
        icmp_ln64_1_reg_1066_pp0_iter3_reg <= icmp_ln64_1_reg_1066_pp0_iter2_reg;
        icmp_ln64_1_reg_1066_pp0_iter4_reg <= icmp_ln64_1_reg_1066_pp0_iter3_reg;
        icmp_ln64_1_reg_1066_pp0_iter5_reg <= icmp_ln64_1_reg_1066_pp0_iter4_reg;
        icmp_ln64_1_reg_1066_pp0_iter6_reg <= icmp_ln64_1_reg_1066_pp0_iter5_reg;
        icmp_ln64_reg_1040_pp0_iter2_reg <= icmp_ln64_reg_1040;
        icmp_ln64_reg_1040_pp0_iter3_reg <= icmp_ln64_reg_1040_pp0_iter2_reg;
        icmp_ln64_reg_1040_pp0_iter4_reg <= icmp_ln64_reg_1040_pp0_iter3_reg;
        icmp_ln64_reg_1040_pp0_iter5_reg <= icmp_ln64_reg_1040_pp0_iter4_reg;
        icmp_ln64_reg_1040_pp0_iter6_reg <= icmp_ln64_reg_1040_pp0_iter5_reg;
        icmp_ln92_reg_1095 <= icmp_ln92_fu_570_p2;
        icmp_ln92_reg_1095_pp0_iter3_reg <= icmp_ln92_reg_1095;
        icmp_ln92_reg_1095_pp0_iter4_reg <= icmp_ln92_reg_1095_pp0_iter3_reg;
        icmp_ln92_reg_1095_pp0_iter5_reg <= icmp_ln92_reg_1095_pp0_iter4_reg;
        icmp_ln92_reg_1095_pp0_iter6_reg <= icmp_ln92_reg_1095_pp0_iter5_reg;
        in_pkt_data_reg_1045_pp0_iter2_reg <= in_pkt_data_reg_1045;
        in_pkt_data_reg_1045_pp0_iter3_reg <= in_pkt_data_reg_1045_pp0_iter2_reg;
        in_pkt_data_reg_1045_pp0_iter4_reg <= in_pkt_data_reg_1045_pp0_iter3_reg;
        linebuf0_addr_reg_1076 <= zext_ln10_reg_1052;
        p12_reg_1087 <= p12_fu_550_p3;
        p12_reg_1087_pp0_iter3_reg <= p12_reg_1087;
        p12_reg_1087_pp0_iter4_reg <= p12_reg_1087_pp0_iter3_reg;
        reuse_select32_reg_1100 <= reuse_select32_fu_590_p3;
        reuse_select32_reg_1100_pp0_iter4_reg <= reuse_select32_reg_1100;
        sub_ln81_reg_1112 <= sub_ln81_fu_675_p2;
        tmp_2_reg_1129 <= gx_fu_766_p2[32'd10];
        tmp_3_reg_1134 <= gy_fu_781_p2[32'd10];
        trunc_ln78_reg_1117 <= trunc_ln78_fu_772_p1;
        trunc_ln82_reg_1123 <= trunc_ln82_fu_787_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln53_reg_1035 <= add_ln53_fu_416_p2;
        and_ln95_reg_1071 <= and_ln95_fu_495_p2;
        icmp_ln53_reg_1030 <= icmp_ln53_fu_397_p2;
        icmp_ln64_1_reg_1066 <= icmp_ln64_1_fu_484_p2;
        icmp_ln64_reg_1040 <= icmp_ln64_fu_453_p2;
        in_pkt_data_reg_1045 <= in_stream_TDATA;
        zext_ln10_reg_1052[10 : 0] <= zext_ln10_fu_469_p1[10 : 0];
        zext_ln53_1_cast_reg_1021[10 : 0] <= zext_ln53_1_cast_fu_295_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln51_reg_1026 <= icmp_ln51_fu_377_p2;
        icmp_ln51_reg_1026_pp0_iter1_reg <= icmp_ln51_reg_1026;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln51_reg_1026_pp0_iter2_reg <= icmp_ln51_reg_1026_pp0_iter1_reg;
        icmp_ln51_reg_1026_pp0_iter3_reg <= icmp_ln51_reg_1026_pp0_iter2_reg;
        icmp_ln51_reg_1026_pp0_iter4_reg <= icmp_ln51_reg_1026_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_377_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter4_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 22'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_168;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln51_reg_1026 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln51_reg_1026 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        linebuf0_ce0_local = 1'b1;
    end else begin
        linebuf0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        linebuf0_ce1_local = 1'b1;
    end else begin
        linebuf0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln51_reg_1026_pp0_iter2_reg == 1'd0))) begin
        linebuf0_we1_local = 1'b1;
    end else begin
        linebuf0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln51_reg_1026 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf1_ce1_local = 1'b1;
    end else begin
        linebuf1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln51_reg_1026 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf1_we1_local = 1'b1;
    end else begin
        linebuf1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_854_p2 = (trunc_ln5_fu_827_p1 + trunc_ln84_fu_842_p1);

assign add_ln51_1_fu_383_p2 = (ap_sig_allocacmp_indvar_flatten_load + 22'd1);

assign add_ln51_2_fu_421_p2 = (row_fu_164 + 11'd1);

assign add_ln53_fu_416_p2 = (idx_fu_160 + zext_ln53_1_cast_reg_1021);

assign add_ln76_1_fu_740_p2 = (zext_ln76_3_fu_737_p1 + zext_ln80_fu_713_p1);

assign add_ln76_fu_629_p2 = (zext_ln77_1_fu_625_p1 + zext_ln76_1_fu_617_p1);

assign add_ln78_fu_756_p2 = (zext_ln77_2_fu_724_p1 + zext_ln77_4_fu_731_p1);

assign add_ln80_fu_659_p2 = (zext_ln81_fu_655_p1 + zext_ln77_fu_621_p1);

assign addr_cmp31_fu_534_p2 = ((reuse_addr_reg28_fu_124 == zext_ln10_reg_1052) ? 1'b1 : 1'b0);

assign addr_cmp_fu_545_p2 = ((reuse_addr_reg_fu_132 == zext_ln10_reg_1052) ? 1'b1 : 1'b0);

assign and_ln64_fu_882_p2 = (icmp_ln64_reg_1040_pp0_iter6_reg & icmp_ln64_1_reg_1066_pp0_iter6_reg);

assign and_ln95_fu_495_p2 = (icmp_ln95_fu_459_p2 & icmp_ln95_1_fu_490_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((icmp_ln51_reg_1026 == 1'd0) & (in_stream_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign col_4_fu_501_p2 = (select_ln51_fu_408_p3 + 11'd1);

assign gx_fu_766_p2 = (zext_ln78_fu_762_p1 + sub_ln77_fu_750_p2);

assign gy_bot_fu_776_p2 = (sub_ln81_reg_1112 + zext_ln76_2_fu_734_p1);

assign gy_fu_781_p2 = (gy_bot_fu_776_p2 - zext_ln77_3_fu_728_p1);

assign gy_top_fu_669_p2 = (zext_ln80_2_fu_665_p1 - zext_ln76_fu_613_p1);

assign icmp_ln10_fu_876_p2 = ((tmp_4_fu_866_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_377_p2 = ((ap_sig_allocacmp_indvar_flatten_load == mul_ln95) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_397_p2 = ((col_fu_144 == width) ? 1'b1 : 1'b0);

assign icmp_ln64_1_fu_484_p2 = ((tmp_1_fu_474_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_453_p2 = ((tmp_fu_443_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_570_p2 = ((select_ln51_1_fu_525_p3 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln95_1_fu_490_p2 = ((select_ln51_fu_408_p3 == add_ln51) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_459_p2 = ((select_ln51_2_fu_427_p3 == add_ln95) ? 1'b1 : 1'b0);

assign idx_3_fu_576_p2 = (select_ln51_1_fu_525_p3 + 22'd1);

assign linebuf0_address0 = zext_ln10_reg_1052;

assign linebuf0_address1 = linebuf0_addr_reg_1076;

assign linebuf0_ce0 = linebuf0_ce0_local;

assign linebuf0_ce1 = linebuf0_ce1_local;

assign linebuf0_d1 = p12_reg_1087;

assign linebuf0_we1 = linebuf0_we1_local;

assign linebuf1_address1 = zext_ln10_fu_469_p1;

assign linebuf1_ce1 = linebuf1_ce1_local;

assign linebuf1_d1 = in_stream_TDATA;

assign linebuf1_we1 = linebuf1_we1_local;

assign mag_fu_860_p2 = (zext_ln84_fu_846_p1 + zext_ln84_1_fu_850_p1);

assign out_pix_fu_886_p3 = ((icmp_ln10_reg_1144[0:0] == 1'b1) ? 8'd255 : add_ln10_reg_1139);

assign out_stream_TDATA = ((and_ln64_fu_882_p2[0:0] == 1'b1) ? out_pix_fu_886_p3 : 8'd0);

assign out_stream_TDEST = 1'd0;

assign out_stream_TID = 1'd0;

assign out_stream_TKEEP = 1'd1;

assign out_stream_TLAST = and_ln95_reg_1071_pp0_iter6_reg;

assign out_stream_TSTRB = 1'd1;

assign out_stream_TUSER = icmp_ln92_reg_1095_pp0_iter6_reg;

assign p12_fu_550_p3 = ((addr_cmp_fu_545_p2[0:0] == 1'b1) ? reuse_reg_fu_136 : linebuf1_q1);

assign reuse_select32_fu_590_p3 = ((addr_cmp31_reg_1082[0:0] == 1'b1) ? reuse_reg27_fu_128 : linebuf0_q0);

assign select_ln51_1_fu_525_p3 = ((icmp_ln53_reg_1030[0:0] == 1'b1) ? add_ln53_reg_1035 : idx_1_fu_140);

assign select_ln51_2_fu_427_p3 = ((icmp_ln53_fu_397_p2[0:0] == 1'b1) ? add_ln51_2_fu_421_p2 : row_fu_164);

assign select_ln51_3_fu_435_p3 = ((icmp_ln53_fu_397_p2[0:0] == 1'b1) ? add_ln53_fu_416_p2 : idx_fu_160);

assign select_ln51_fu_408_p3 = ((icmp_ln53_fu_397_p2[0:0] == 1'b1) ? 11'd0 : col_fu_144);

assign select_ln5_fu_836_p3 = ((tmp_3_reg_1134[0:0] == 1'b1) ? sub_ln5_1_fu_831_p2 : trunc_ln82_reg_1123);

assign shl_ln1_fu_717_p3 = {{p12_reg_1087_pp0_iter4_reg}, {1'd0}};

assign shl_ln2_fu_635_p3 = {{p01_fu_172}, {1'd0}};

assign shl_ln3_fu_647_p3 = {{p21_fu_180}, {1'd0}};

assign shl_ln_fu_705_p3 = {{p10_fu_152}, {1'd0}};

assign sub_ln5_1_fu_831_p2 = (10'd0 - trunc_ln82_reg_1123);

assign sub_ln5_fu_816_p2 = (10'd0 - trunc_ln78_reg_1117);

assign sub_ln77_fu_750_p2 = (zext_ln76_2_fu_734_p1 - zext_ln77_5_fu_746_p1);

assign sub_ln81_fu_675_p2 = (gy_top_fu_669_p2 - zext_ln80_1_fu_643_p1);

assign tmp_1_fu_474_p4 = {{select_ln51_fu_408_p3[10:1]}};

assign tmp_4_fu_866_p4 = {{mag_fu_860_p2[10:8]}};

assign tmp_fu_443_p4 = {{select_ln51_2_fu_427_p3[10:1]}};

assign trunc_ln5_fu_827_p1 = x_1_fu_821_p3[7:0];

assign trunc_ln78_fu_772_p1 = gx_fu_766_p2[9:0];

assign trunc_ln82_fu_787_p1 = gy_fu_781_p2[9:0];

assign trunc_ln84_fu_842_p1 = select_ln5_fu_836_p3[7:0];

assign x_1_fu_821_p3 = ((tmp_2_reg_1129[0:0] == 1'b1) ? sub_ln5_fu_816_p2 : trunc_ln78_reg_1117);

assign zext_ln10_fu_469_p1 = select_ln51_fu_408_p3;

assign zext_ln53_1_cast_fu_295_p1 = zext_ln53_1;

assign zext_ln76_1_fu_617_p1 = p_0_0_08371182_fu_148;

assign zext_ln76_2_fu_734_p1 = in_pkt_data_reg_1045_pp0_iter4_reg;

assign zext_ln76_3_fu_737_p1 = add_ln76_reg_1107;

assign zext_ln76_fu_613_p1 = p_0_0_08371182_fu_148;

assign zext_ln77_1_fu_625_p1 = p_0_0_08331186_fu_156;

assign zext_ln77_2_fu_724_p1 = shl_ln1_fu_717_p3;

assign zext_ln77_3_fu_728_p1 = reuse_select32_reg_1100_pp0_iter4_reg;

assign zext_ln77_4_fu_731_p1 = reuse_select32_reg_1100_pp0_iter4_reg;

assign zext_ln77_5_fu_746_p1 = add_ln76_1_fu_740_p2;

assign zext_ln77_fu_621_p1 = p_0_0_08331186_fu_156;

assign zext_ln78_fu_762_p1 = add_ln78_fu_756_p2;

assign zext_ln80_1_fu_643_p1 = shl_ln2_fu_635_p3;

assign zext_ln80_2_fu_665_p1 = add_ln80_fu_659_p2;

assign zext_ln80_fu_713_p1 = shl_ln_fu_705_p3;

assign zext_ln81_fu_655_p1 = shl_ln3_fu_647_p3;

assign zext_ln84_1_fu_850_p1 = select_ln5_fu_836_p3;

assign zext_ln84_fu_846_p1 = x_1_fu_821_p3;

always @ (posedge ap_clk) begin
    zext_ln53_1_cast_reg_1021[21:11] <= 11'b00000000000;
    zext_ln10_reg_1052[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //sobel_top_sobel_core_Pipeline_row_loop_col_loop
