-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_top_sobel_core_Pipeline_row_loop_col_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (10 downto 0);
    mul_ln95 : IN STD_LOGIC_VECTOR (21 downto 0);
    zext_ln53_1 : IN STD_LOGIC_VECTOR (10 downto 0);
    add_ln95 : IN STD_LOGIC_VECTOR (10 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    linebuf0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf0_ce0 : OUT STD_LOGIC;
    linebuf0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    linebuf0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf0_ce1 : OUT STD_LOGIC;
    linebuf0_we1 : OUT STD_LOGIC;
    linebuf0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf1_ce1 : OUT STD_LOGIC;
    linebuf1_we1 : OUT STD_LOGIC;
    linebuf1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    add_ln51 : IN STD_LOGIC_VECTOR (10 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of sobel_top_sobel_core_Pipeline_row_loop_col_loop is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv22_1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln51_reg_1026 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln51_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal zext_ln53_1_cast_fu_295_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln53_1_cast_reg_1021 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln51_reg_1026_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_reg_1026_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_reg_1026_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_reg_1026_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_1030 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln53_fu_416_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln53_reg_1035 : STD_LOGIC_VECTOR (21 downto 0);
    signal icmp_ln64_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_1040 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_1040_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_1040_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_1040_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_1040_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_1040_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal in_pkt_data_reg_1045 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pkt_data_reg_1045_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pkt_data_reg_1045_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pkt_data_reg_1045_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln10_fu_469_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln10_reg_1052 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln64_1_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_reg_1066 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_reg_1066_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_reg_1066_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_reg_1066_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_reg_1066_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_reg_1066_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln95_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln95_reg_1071 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln95_reg_1071_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln95_reg_1071_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln95_reg_1071_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln95_reg_1071_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln95_reg_1071_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal linebuf0_addr_reg_1076 : STD_LOGIC_VECTOR (10 downto 0);
    signal addr_cmp31_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp31_reg_1082 : STD_LOGIC_VECTOR (0 downto 0);
    signal p12_fu_550_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p12_reg_1087 : STD_LOGIC_VECTOR (7 downto 0);
    signal p12_reg_1087_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p12_reg_1087_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln92_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_1095 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_1095_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_1095_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_1095_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_1095_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal reuse_select32_fu_590_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select32_reg_1100 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select32_reg_1100_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln76_fu_629_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_reg_1107 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln81_fu_675_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln81_reg_1112 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln78_fu_772_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln78_reg_1117 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln82_fu_787_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln82_reg_1123 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_reg_1129 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1134 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln10_fu_854_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln10_reg_1139 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln10_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_reg_1144 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter5_stage0 : STD_LOGIC;
    signal reuse_addr_reg28_fu_124 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg27_fu_128 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal reuse_addr_reg_fu_132 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_136 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal idx_1_fu_140 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    signal idx_3_fu_576_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal col_fu_144 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal col_4_fu_501_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_0_0_08371182_fu_148 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p10_fu_152 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_08331186_fu_156 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal idx_fu_160 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    signal select_ln51_3_fu_435_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal row_fu_164 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal select_ln51_2_fu_427_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal indvar_flatten_fu_168 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    signal add_ln51_1_fu_383_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p01_fu_172 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_08341185_fu_176 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p21_fu_180 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal linebuf1_ce1_local : STD_LOGIC;
    signal linebuf1_we1_local : STD_LOGIC;
    signal linebuf0_ce0_local : STD_LOGIC;
    signal linebuf0_we1_local : STD_LOGIC;
    signal linebuf0_ce1_local : STD_LOGIC;
    signal add_ln51_2_fu_421_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_443_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_fu_408_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_474_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln95_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_1_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_fu_545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln51_1_fu_525_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln77_1_fu_625_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln76_1_fu_617_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln2_fu_635_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln3_fu_647_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_fu_655_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln77_fu_621_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln80_fu_659_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln80_2_fu_665_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln76_fu_613_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_top_fu_669_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln80_1_fu_643_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_fu_705_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1_fu_717_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln76_3_fu_737_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln80_fu_713_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln76_1_fu_740_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln76_2_fu_734_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln77_5_fu_746_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln77_2_fu_724_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln77_4_fu_731_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln78_fu_756_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln78_fu_762_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln77_fu_750_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_fu_766_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_bot_fu_776_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln77_3_fu_728_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_fu_781_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln5_fu_816_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_1_fu_821_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln5_1_fu_831_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln5_fu_836_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln5_fu_827_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln84_fu_842_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln84_fu_846_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln84_1_fu_850_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mag_fu_860_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_866_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln64_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pix_fu_886_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component sobel_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter5_stage0)) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    col_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    col_fu_144 <= ap_const_lv11_0;
                elsif (((icmp_ln51_reg_1026 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    col_fu_144 <= col_4_fu_501_p2;
                end if;
            end if; 
        end if;
    end process;

    idx_1_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    idx_1_fu_140 <= ap_const_lv22_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter1_reg = ap_const_lv1_0))) then 
                    idx_1_fu_140 <= idx_3_fu_576_p2;
                end if;
            end if; 
        end if;
    end process;

    idx_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    idx_fu_160 <= ap_const_lv22_0;
                elsif (((icmp_ln51_reg_1026 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    idx_fu_160 <= select_ln51_3_fu_435_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln51_fu_377_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_168 <= add_ln51_1_fu_383_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_168 <= ap_const_lv22_0;
                end if;
            end if; 
        end if;
    end process;

    p01_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p01_fu_172 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter3_reg = ap_const_lv1_0))) then 
                    p01_fu_172 <= reuse_select32_reg_1100;
                end if;
            end if; 
        end if;
    end process;

    p10_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p10_fu_152 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter4_reg = ap_const_lv1_0))) then 
                    p10_fu_152 <= p_0_0_08341185_fu_176;
                end if;
            end if; 
        end if;
    end process;

    p21_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p21_fu_180 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter3_reg = ap_const_lv1_0))) then 
                    p21_fu_180 <= in_pkt_data_reg_1045_pp0_iter3_reg;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_08331186_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_08331186_fu_156 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter3_reg = ap_const_lv1_0))) then 
                    p_0_0_08331186_fu_156 <= p21_fu_180;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_08341185_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_08341185_fu_176 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter4_reg = ap_const_lv1_0))) then 
                    p_0_0_08341185_fu_176 <= p12_reg_1087_pp0_iter4_reg;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_08371182_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    p_0_0_08371182_fu_148 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter3_reg = ap_const_lv1_0))) then 
                    p_0_0_08371182_fu_148 <= p01_fu_172;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg28_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg28_fu_124 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter1_reg = ap_const_lv1_0))) then 
                    reuse_addr_reg28_fu_124 <= zext_ln10_reg_1052;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg_fu_132 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter1_reg = ap_const_lv1_0))) then 
                    reuse_addr_reg_fu_132 <= zext_ln10_reg_1052;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg27_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg27_fu_128 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter2_reg = ap_const_lv1_0))) then 
                    reuse_reg27_fu_128 <= p12_reg_1087;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_136 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter1_reg = ap_const_lv1_0))) then 
                    reuse_reg_fu_136 <= in_pkt_data_reg_1045;
                end if;
            end if; 
        end if;
    end process;

    row_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    row_fu_164 <= ap_const_lv11_0;
                elsif (((icmp_ln51_reg_1026 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    row_fu_164 <= select_ln51_2_fu_427_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln10_reg_1139 <= add_ln10_fu_854_p2;
                add_ln76_reg_1107 <= add_ln76_fu_629_p2;
                addr_cmp31_reg_1082 <= addr_cmp31_fu_534_p2;
                and_ln95_reg_1071_pp0_iter2_reg <= and_ln95_reg_1071;
                and_ln95_reg_1071_pp0_iter3_reg <= and_ln95_reg_1071_pp0_iter2_reg;
                and_ln95_reg_1071_pp0_iter4_reg <= and_ln95_reg_1071_pp0_iter3_reg;
                and_ln95_reg_1071_pp0_iter5_reg <= and_ln95_reg_1071_pp0_iter4_reg;
                and_ln95_reg_1071_pp0_iter6_reg <= and_ln95_reg_1071_pp0_iter5_reg;
                icmp_ln10_reg_1144 <= icmp_ln10_fu_876_p2;
                icmp_ln64_1_reg_1066_pp0_iter2_reg <= icmp_ln64_1_reg_1066;
                icmp_ln64_1_reg_1066_pp0_iter3_reg <= icmp_ln64_1_reg_1066_pp0_iter2_reg;
                icmp_ln64_1_reg_1066_pp0_iter4_reg <= icmp_ln64_1_reg_1066_pp0_iter3_reg;
                icmp_ln64_1_reg_1066_pp0_iter5_reg <= icmp_ln64_1_reg_1066_pp0_iter4_reg;
                icmp_ln64_1_reg_1066_pp0_iter6_reg <= icmp_ln64_1_reg_1066_pp0_iter5_reg;
                icmp_ln64_reg_1040_pp0_iter2_reg <= icmp_ln64_reg_1040;
                icmp_ln64_reg_1040_pp0_iter3_reg <= icmp_ln64_reg_1040_pp0_iter2_reg;
                icmp_ln64_reg_1040_pp0_iter4_reg <= icmp_ln64_reg_1040_pp0_iter3_reg;
                icmp_ln64_reg_1040_pp0_iter5_reg <= icmp_ln64_reg_1040_pp0_iter4_reg;
                icmp_ln64_reg_1040_pp0_iter6_reg <= icmp_ln64_reg_1040_pp0_iter5_reg;
                icmp_ln92_reg_1095 <= icmp_ln92_fu_570_p2;
                icmp_ln92_reg_1095_pp0_iter3_reg <= icmp_ln92_reg_1095;
                icmp_ln92_reg_1095_pp0_iter4_reg <= icmp_ln92_reg_1095_pp0_iter3_reg;
                icmp_ln92_reg_1095_pp0_iter5_reg <= icmp_ln92_reg_1095_pp0_iter4_reg;
                icmp_ln92_reg_1095_pp0_iter6_reg <= icmp_ln92_reg_1095_pp0_iter5_reg;
                in_pkt_data_reg_1045_pp0_iter2_reg <= in_pkt_data_reg_1045;
                in_pkt_data_reg_1045_pp0_iter3_reg <= in_pkt_data_reg_1045_pp0_iter2_reg;
                in_pkt_data_reg_1045_pp0_iter4_reg <= in_pkt_data_reg_1045_pp0_iter3_reg;
                linebuf0_addr_reg_1076 <= zext_ln10_reg_1052(11 - 1 downto 0);
                p12_reg_1087 <= p12_fu_550_p3;
                p12_reg_1087_pp0_iter3_reg <= p12_reg_1087;
                p12_reg_1087_pp0_iter4_reg <= p12_reg_1087_pp0_iter3_reg;
                reuse_select32_reg_1100 <= reuse_select32_fu_590_p3;
                reuse_select32_reg_1100_pp0_iter4_reg <= reuse_select32_reg_1100;
                sub_ln81_reg_1112 <= sub_ln81_fu_675_p2;
                tmp_2_reg_1129 <= gx_fu_766_p2(10 downto 10);
                tmp_3_reg_1134 <= gy_fu_781_p2(10 downto 10);
                trunc_ln78_reg_1117 <= trunc_ln78_fu_772_p1;
                trunc_ln82_reg_1123 <= trunc_ln82_fu_787_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln53_reg_1035 <= add_ln53_fu_416_p2;
                and_ln95_reg_1071 <= and_ln95_fu_495_p2;
                icmp_ln53_reg_1030 <= icmp_ln53_fu_397_p2;
                icmp_ln64_1_reg_1066 <= icmp_ln64_1_fu_484_p2;
                icmp_ln64_reg_1040 <= icmp_ln64_fu_453_p2;
                in_pkt_data_reg_1045 <= in_stream_TDATA;
                    zext_ln10_reg_1052(10 downto 0) <= zext_ln10_fu_469_p1(10 downto 0);
                    zext_ln53_1_cast_reg_1021(10 downto 0) <= zext_ln53_1_cast_fu_295_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln51_reg_1026 <= icmp_ln51_fu_377_p2;
                icmp_ln51_reg_1026_pp0_iter1_reg <= icmp_ln51_reg_1026;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                icmp_ln51_reg_1026_pp0_iter2_reg <= icmp_ln51_reg_1026_pp0_iter1_reg;
                icmp_ln51_reg_1026_pp0_iter3_reg <= icmp_ln51_reg_1026_pp0_iter2_reg;
                icmp_ln51_reg_1026_pp0_iter4_reg <= icmp_ln51_reg_1026_pp0_iter3_reg;
            end if;
        end if;
    end process;
    zext_ln53_1_cast_reg_1021(21 downto 11) <= "00000000000";
    zext_ln10_reg_1052(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln10_fu_854_p2 <= std_logic_vector(unsigned(trunc_ln5_fu_827_p1) + unsigned(trunc_ln84_fu_842_p1));
    add_ln51_1_fu_383_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv22_1));
    add_ln51_2_fu_421_p2 <= std_logic_vector(unsigned(row_fu_164) + unsigned(ap_const_lv11_1));
    add_ln53_fu_416_p2 <= std_logic_vector(unsigned(idx_fu_160) + unsigned(zext_ln53_1_cast_reg_1021));
    add_ln76_1_fu_740_p2 <= std_logic_vector(unsigned(zext_ln76_3_fu_737_p1) + unsigned(zext_ln80_fu_713_p1));
    add_ln76_fu_629_p2 <= std_logic_vector(unsigned(zext_ln77_1_fu_625_p1) + unsigned(zext_ln76_1_fu_617_p1));
    add_ln78_fu_756_p2 <= std_logic_vector(unsigned(zext_ln77_2_fu_724_p1) + unsigned(zext_ln77_4_fu_731_p1));
    add_ln80_fu_659_p2 <= std_logic_vector(unsigned(zext_ln81_fu_655_p1) + unsigned(zext_ln77_fu_621_p1));
    addr_cmp31_fu_534_p2 <= "1" when (reuse_addr_reg28_fu_124 = zext_ln10_reg_1052) else "0";
    addr_cmp_fu_545_p2 <= "1" when (reuse_addr_reg_fu_132 = zext_ln10_reg_1052) else "0";
    and_ln64_fu_882_p2 <= (icmp_ln64_reg_1040_pp0_iter6_reg and icmp_ln64_1_reg_1066_pp0_iter6_reg);
    and_ln95_fu_495_p2 <= (icmp_ln95_fu_459_p2 and icmp_ln95_1_fu_490_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter7, out_stream_TREADY, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter7, out_stream_TREADY, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter7, out_stream_TREADY, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter7, out_stream_TREADY, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(in_stream_TVALID, icmp_ln51_reg_1026)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= ((icmp_ln51_reg_1026 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln51_fu_377_p2)
    begin
        if (((icmp_ln51_fu_377_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter5_stage0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone, icmp_ln51_reg_1026_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter4_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten_fu_168, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv22_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_168;
        end if; 
    end process;

    col_4_fu_501_p2 <= std_logic_vector(unsigned(select_ln51_fu_408_p3) + unsigned(ap_const_lv11_1));
    gx_fu_766_p2 <= std_logic_vector(unsigned(zext_ln78_fu_762_p1) + unsigned(sub_ln77_fu_750_p2));
    gy_bot_fu_776_p2 <= std_logic_vector(unsigned(sub_ln81_reg_1112) + unsigned(zext_ln76_2_fu_734_p1));
    gy_fu_781_p2 <= std_logic_vector(unsigned(gy_bot_fu_776_p2) - unsigned(zext_ln77_3_fu_728_p1));
    gy_top_fu_669_p2 <= std_logic_vector(unsigned(zext_ln80_2_fu_665_p1) - unsigned(zext_ln76_fu_613_p1));
    icmp_ln10_fu_876_p2 <= "0" when (tmp_4_fu_866_p4 = ap_const_lv3_0) else "1";
    icmp_ln51_fu_377_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = mul_ln95) else "0";
    icmp_ln53_fu_397_p2 <= "1" when (col_fu_144 = width) else "0";
    icmp_ln64_1_fu_484_p2 <= "0" when (tmp_1_fu_474_p4 = ap_const_lv10_0) else "1";
    icmp_ln64_fu_453_p2 <= "0" when (tmp_fu_443_p4 = ap_const_lv10_0) else "1";
    icmp_ln92_fu_570_p2 <= "1" when (select_ln51_1_fu_525_p3 = ap_const_lv22_0) else "0";
    icmp_ln95_1_fu_490_p2 <= "1" when (select_ln51_fu_408_p3 = add_ln51) else "0";
    icmp_ln95_fu_459_p2 <= "1" when (select_ln51_2_fu_427_p3 = add_ln95) else "0";
    idx_3_fu_576_p2 <= std_logic_vector(unsigned(select_ln51_1_fu_525_p3) + unsigned(ap_const_lv22_1));

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, in_stream_TVALID, icmp_ln51_reg_1026, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln51_reg_1026 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln51_reg_1026, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln51_reg_1026 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    linebuf0_address0 <= zext_ln10_reg_1052(11 - 1 downto 0);
    linebuf0_address1 <= linebuf0_addr_reg_1076;
    linebuf0_ce0 <= linebuf0_ce0_local;

    linebuf0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linebuf0_ce0_local <= ap_const_logic_1;
        else 
            linebuf0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf0_ce1 <= linebuf0_ce1_local;

    linebuf0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            linebuf0_ce1_local <= ap_const_logic_1;
        else 
            linebuf0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf0_d1 <= p12_reg_1087;
    linebuf0_we1 <= linebuf0_we1_local;

    linebuf0_we1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1, icmp_ln51_reg_1026_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln51_reg_1026_pp0_iter2_reg = ap_const_lv1_0))) then 
            linebuf0_we1_local <= ap_const_logic_1;
        else 
            linebuf0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf1_address1 <= zext_ln10_fu_469_p1(11 - 1 downto 0);
    linebuf1_ce1 <= linebuf1_ce1_local;

    linebuf1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln51_reg_1026, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln51_reg_1026 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf1_ce1_local <= ap_const_logic_1;
        else 
            linebuf1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    linebuf1_d1 <= in_stream_TDATA;
    linebuf1_we1 <= linebuf1_we1_local;

    linebuf1_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln51_reg_1026, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln51_reg_1026 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf1_we1_local <= ap_const_logic_1;
        else 
            linebuf1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    mag_fu_860_p2 <= std_logic_vector(unsigned(zext_ln84_fu_846_p1) + unsigned(zext_ln84_1_fu_850_p1));
    out_pix_fu_886_p3 <= 
        ap_const_lv8_FF when (icmp_ln10_reg_1144(0) = '1') else 
        add_ln10_reg_1139;
    out_stream_TDATA <= 
        out_pix_fu_886_p3 when (and_ln64_fu_882_p2(0) = '1') else 
        ap_const_lv8_0;

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter7, out_stream_TREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDEST <= ap_const_lv1_0;
    out_stream_TID <= ap_const_lv1_0;
    out_stream_TKEEP <= ap_const_lv1_1;
    out_stream_TLAST <= and_ln95_reg_1071_pp0_iter6_reg;
    out_stream_TSTRB <= ap_const_lv1_1;
    out_stream_TUSER <= icmp_ln92_reg_1095_pp0_iter6_reg;

    out_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    p12_fu_550_p3 <= 
        reuse_reg_fu_136 when (addr_cmp_fu_545_p2(0) = '1') else 
        linebuf1_q1;
    reuse_select32_fu_590_p3 <= 
        reuse_reg27_fu_128 when (addr_cmp31_reg_1082(0) = '1') else 
        linebuf0_q0;
    select_ln51_1_fu_525_p3 <= 
        add_ln53_reg_1035 when (icmp_ln53_reg_1030(0) = '1') else 
        idx_1_fu_140;
    select_ln51_2_fu_427_p3 <= 
        add_ln51_2_fu_421_p2 when (icmp_ln53_fu_397_p2(0) = '1') else 
        row_fu_164;
    select_ln51_3_fu_435_p3 <= 
        add_ln53_fu_416_p2 when (icmp_ln53_fu_397_p2(0) = '1') else 
        idx_fu_160;
    select_ln51_fu_408_p3 <= 
        ap_const_lv11_0 when (icmp_ln53_fu_397_p2(0) = '1') else 
        col_fu_144;
    select_ln5_fu_836_p3 <= 
        sub_ln5_1_fu_831_p2 when (tmp_3_reg_1134(0) = '1') else 
        trunc_ln82_reg_1123;
    shl_ln1_fu_717_p3 <= (p12_reg_1087_pp0_iter4_reg & ap_const_lv1_0);
    shl_ln2_fu_635_p3 <= (p01_fu_172 & ap_const_lv1_0);
    shl_ln3_fu_647_p3 <= (p21_fu_180 & ap_const_lv1_0);
    shl_ln_fu_705_p3 <= (p10_fu_152 & ap_const_lv1_0);
    sub_ln5_1_fu_831_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(trunc_ln82_reg_1123));
    sub_ln5_fu_816_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(trunc_ln78_reg_1117));
    sub_ln77_fu_750_p2 <= std_logic_vector(unsigned(zext_ln76_2_fu_734_p1) - unsigned(zext_ln77_5_fu_746_p1));
    sub_ln81_fu_675_p2 <= std_logic_vector(unsigned(gy_top_fu_669_p2) - unsigned(zext_ln80_1_fu_643_p1));
    tmp_1_fu_474_p4 <= select_ln51_fu_408_p3(10 downto 1);
    tmp_4_fu_866_p4 <= mag_fu_860_p2(10 downto 8);
    tmp_fu_443_p4 <= select_ln51_2_fu_427_p3(10 downto 1);
    trunc_ln5_fu_827_p1 <= x_1_fu_821_p3(8 - 1 downto 0);
    trunc_ln78_fu_772_p1 <= gx_fu_766_p2(10 - 1 downto 0);
    trunc_ln82_fu_787_p1 <= gy_fu_781_p2(10 - 1 downto 0);
    trunc_ln84_fu_842_p1 <= select_ln5_fu_836_p3(8 - 1 downto 0);
    x_1_fu_821_p3 <= 
        sub_ln5_fu_816_p2 when (tmp_2_reg_1129(0) = '1') else 
        trunc_ln78_reg_1117;
    zext_ln10_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_fu_408_p3),64));
    zext_ln53_1_cast_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln53_1),22));
    zext_ln76_1_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_08371182_fu_148),9));
    zext_ln76_2_fu_734_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pkt_data_reg_1045_pp0_iter4_reg),11));
    zext_ln76_3_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_reg_1107),10));
    zext_ln76_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_08371182_fu_148),11));
    zext_ln77_1_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_08331186_fu_156),9));
    zext_ln77_2_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_717_p3),10));
    zext_ln77_3_fu_728_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select32_reg_1100_pp0_iter4_reg),11));
    zext_ln77_4_fu_731_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reuse_select32_reg_1100_pp0_iter4_reg),10));
    zext_ln77_5_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_1_fu_740_p2),11));
    zext_ln77_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_08331186_fu_156),10));
    zext_ln78_fu_762_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln78_fu_756_p2),11));
    zext_ln80_1_fu_643_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_635_p3),11));
    zext_ln80_2_fu_665_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln80_fu_659_p2),11));
    zext_ln80_fu_713_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_705_p3),10));
    zext_ln81_fu_655_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln3_fu_647_p3),10));
    zext_ln84_1_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln5_fu_836_p3),11));
    zext_ln84_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_1_fu_821_p3),11));
end behav;
