// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module sobel_top_sobel_core_Pipeline_VITIS_LOOP_47_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        out_stream_TREADY,
        total,
        width,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        linebuf0_address0,
        linebuf0_ce0,
        linebuf0_we0,
        linebuf0_d0,
        linebuf0_q0,
        linebuf1_address0,
        linebuf1_ce0,
        linebuf1_we0,
        linebuf1_d0,
        linebuf1_q0,
        empty,
        add_ln84,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [21:0] total;
input  [10:0] width;
input  [7:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [10:0] linebuf0_address0;
output   linebuf0_ce0;
output   linebuf0_we0;
output  [7:0] linebuf0_d0;
input  [7:0] linebuf0_q0;
output  [10:0] linebuf1_address0;
output   linebuf1_ce0;
output   linebuf1_we0;
output  [7:0] linebuf1_d0;
input  [7:0] linebuf1_q0;
input  [10:0] empty;
input  [21:0] add_ln84;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;

reg ap_idle;
reg in_stream_TREADY;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln47_reg_842;
reg   [0:0] icmp_ln47_reg_842_pp0_iter26_reg;
reg    ap_block_state28_pp0_stage0_iter27_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_326_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [21:0] width_cast_fu_264_p1;
reg   [21:0] width_cast_reg_829;
reg   [21:0] idx_1_reg_834;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln47_reg_842_pp0_iter1_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter2_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter3_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter4_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter5_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter6_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter7_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter8_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter9_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter10_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter11_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter12_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter13_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter14_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter15_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter16_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter17_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter18_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter19_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter20_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter21_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter22_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter23_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter24_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter25_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter27_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter28_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter29_reg;
reg   [0:0] icmp_ln47_reg_842_pp0_iter30_reg;
wire   [0:0] icmp_ln61_fu_358_p2;
reg   [0:0] icmp_ln61_reg_846;
reg   [0:0] icmp_ln61_reg_846_pp0_iter2_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter3_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter4_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter5_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter6_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter7_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter8_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter9_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter10_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter11_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter12_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter13_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter14_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter15_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter16_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter17_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter18_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter19_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter20_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter21_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter22_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter23_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter24_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter25_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter26_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter27_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter28_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter29_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter30_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter31_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter32_reg;
reg   [0:0] icmp_ln61_reg_846_pp0_iter33_reg;
wire   [0:0] icmp_ln81_fu_363_p2;
reg   [0:0] icmp_ln81_reg_851;
reg   [0:0] icmp_ln81_reg_851_pp0_iter2_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter3_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter4_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter5_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter6_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter7_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter8_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter9_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter10_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter11_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter12_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter13_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter14_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter15_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter16_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter17_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter18_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter19_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter20_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter21_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter22_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter23_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter24_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter25_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter26_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter27_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter28_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter29_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter30_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter31_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter32_reg;
reg   [0:0] icmp_ln81_reg_851_pp0_iter33_reg;
wire   [0:0] icmp_ln84_fu_368_p2;
reg   [0:0] icmp_ln84_reg_856;
reg   [0:0] icmp_ln84_reg_856_pp0_iter2_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter3_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter4_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter5_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter6_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter7_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter8_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter9_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter10_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter11_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter12_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter13_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter14_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter15_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter16_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter17_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter18_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter19_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter20_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter21_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter22_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter23_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter24_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter25_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter26_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter27_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter28_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter29_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter30_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter31_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter32_reg;
reg   [0:0] icmp_ln84_reg_856_pp0_iter33_reg;
wire   [21:0] grp_fu_343_p2;
reg   [21:0] col_reg_861;
reg   [10:0] tmp_4_reg_866;
reg   [7:0] in_pkt_data_reg_871;
reg   [7:0] in_pkt_data_reg_871_pp0_iter28_reg;
reg   [7:0] in_pkt_data_reg_871_pp0_iter29_reg;
reg   [7:0] in_pkt_data_reg_871_pp0_iter30_reg;
reg   [7:0] in_pkt_data_reg_871_pp0_iter31_reg;
wire   [63:0] zext_ln19_fu_387_p1;
reg   [10:0] linebuf0_addr_reg_885;
reg   [10:0] linebuf0_addr_reg_885_pp0_iter28_reg;
wire   [0:0] icmp_ln61_1_fu_420_p2;
reg   [0:0] icmp_ln61_1_reg_905;
reg   [0:0] icmp_ln61_1_reg_905_pp0_iter28_reg;
reg   [0:0] icmp_ln61_1_reg_905_pp0_iter29_reg;
reg   [0:0] icmp_ln61_1_reg_905_pp0_iter30_reg;
reg   [0:0] icmp_ln61_1_reg_905_pp0_iter31_reg;
reg   [0:0] icmp_ln61_1_reg_905_pp0_iter32_reg;
reg   [0:0] icmp_ln61_1_reg_905_pp0_iter33_reg;
wire   [0:0] grp_fu_395_p2;
reg   [0:0] addr_cmp55_reg_910;
reg   [0:0] addr_cmp55_reg_910_pp0_iter29_reg;
reg   [0:0] addr_cmp55_reg_910_pp0_iter30_reg;
wire   [0:0] grp_fu_404_p2;
reg   [0:0] addr_cmp_reg_915;
wire   [7:0] reuse_select_fu_428_p3;
reg   [7:0] reuse_select_reg_920;
reg   [7:0] reuse_select_reg_920_pp0_iter30_reg;
wire   [7:0] reuse_select56_fu_461_p3;
reg   [7:0] reuse_select56_reg_927;
wire   [8:0] tmp_fu_487_p2;
reg   [8:0] tmp_reg_932;
wire   [8:0] add_ln64_fu_493_p2;
reg   [8:0] add_ln64_reg_937;
wire   [8:0] tmp3_fu_507_p2;
reg   [8:0] tmp3_reg_942;
wire   [8:0] sub_ln68_fu_513_p2;
reg   [8:0] sub_ln68_reg_947;
wire   [9:0] trunc_ln62_fu_596_p1;
reg   [9:0] trunc_ln62_reg_952;
wire   [9:0] trunc_ln67_fu_636_p1;
reg   [9:0] trunc_ln67_reg_958;
reg   [0:0] tmp_5_reg_964;
reg   [0:0] tmp_6_reg_969;
wire   [9:0] select_ln12_fu_661_p3;
reg   [9:0] select_ln12_reg_974;
wire   [9:0] select_ln12_1_fu_676_p3;
reg   [9:0] select_ln12_1_reg_979;
reg   [2:0] tmp_7_reg_984;
reg    ap_condition_exit_pp0_iter31_stage0;
reg   [63:0] reuse_addr_reg52_fu_124;
wire    ap_loop_init;
reg   [7:0] reuse_reg51_fu_128;
reg   [63:0] reuse_addr_reg_fu_132;
reg   [7:0] reuse_reg_fu_136;
reg   [21:0] idx_fu_140;
wire   [21:0] idx_2_fu_332_p2;
reg   [21:0] ap_sig_allocacmp_idx_1;
wire    ap_block_pp0_stage0;
reg   [7:0] p_0_0_0157277_fu_144;
reg   [7:0] p_0_0_0155279_fu_148;
reg   [7:0] p_0_0_0153281_fu_152;
reg   [7:0] p_0_0_0156278_fu_156;
reg   [7:0] p_0_0_0154280_fu_160;
reg   [7:0] p_0_0_0152282_fu_164;
reg    ap_block_pp0_stage0_01001_grp1;
reg    linebuf1_ce0_local;
reg    linebuf1_we0_local;
reg    linebuf0_ce0_local;
reg    linebuf0_we0_local;
wire   [10:0] grp_fu_343_p1;
wire   [11:0] p2y_fu_347_p3;
wire   [21:0] zext_ln61_fu_354_p1;
wire   [8:0] zext_ln65_fu_480_p1;
wire   [8:0] p_0_0_0155279_cast_fu_476_p1;
wire   [8:0] zext_ln63_fu_472_p1;
wire   [8:0] zext_ln65_1_fu_483_p1;
wire   [8:0] p_0_0_0152282_cast_fu_503_p1;
wire   [8:0] p_0_0_0156278_cast_fu_499_p1;
wire   [9:0] tmp_1_fu_556_p3;
wire   [9:0] in_pkt_data_cast_fu_553_p1;
wire   [9:0] zext_ln64_fu_567_p1;
wire   [9:0] sub_ln64_fu_570_p2;
wire  signed [10:0] sext_ln64_fu_563_p1;
wire   [10:0] linebuf0_load_cast_fu_547_p1;
wire   [10:0] add_ln65_fu_580_p2;
wire  signed [10:0] sext_ln65_fu_576_p1;
wire  signed [10:0] gx_fu_586_p2;
wire   [9:0] tmp_2_fu_600_p3;
wire  signed [10:0] sext_ln68_fu_607_p1;
wire   [10:0] in_pkt_data_cast1_fu_550_p1;
wire   [10:0] add_ln69_fu_614_p2;
wire  signed [10:0] sext_ln69_fu_611_p1;
wire   [10:0] add_ln69_1_fu_620_p2;
wire  signed [10:0] gy_fu_626_p2;
wire  signed [31:0] sext_ln62_fu_592_p1;
wire  signed [31:0] sext_ln67_fu_632_p1;
wire   [9:0] sub_ln12_fu_656_p2;
wire   [9:0] sub_ln12_1_fu_671_p2;
wire   [10:0] zext_ln10_fu_667_p1;
wire   [10:0] zext_ln71_fu_682_p1;
wire   [10:0] mag_fu_686_p2;
wire   [0:0] xor_ln61_fu_702_p2;
wire   [9:0] add_ln71_fu_712_p2;
wire   [0:0] icmp_ln6_fu_716_p2;
wire   [7:0] trunc_ln7_fu_721_p1;
wire   [0:0] and_ln61_fu_707_p2;
wire   [7:0] out_pix_fu_725_p3;
reg    grp_fu_343_ce;
reg    grp_fu_395_ce;
reg    ap_block_pp0_stage0_00001_grp1;
reg    grp_fu_404_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 reuse_addr_reg52_fu_124 = 64'd0;
#0 reuse_reg51_fu_128 = 8'd0;
#0 reuse_addr_reg_fu_132 = 64'd0;
#0 reuse_reg_fu_136 = 8'd0;
#0 idx_fu_140 = 22'd0;
#0 p_0_0_0157277_fu_144 = 8'd0;
#0 p_0_0_0155279_fu_148 = 8'd0;
#0 p_0_0_0153281_fu_152 = 8'd0;
#0 p_0_0_0156278_fu_156 = 8'd0;
#0 p_0_0_0154280_fu_160 = 8'd0;
#0 p_0_0_0152282_fu_164 = 8'd0;
#0 ap_done_reg = 1'b0;
end

sobel_top_urem_22ns_11ns_22_26_1 #(
    .ID( 1 ),
    .NUM_STAGE( 26 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 22 ))
urem_22ns_11ns_22_26_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(idx_1_reg_834),
    .din1(grp_fu_343_p1),
    .ce(grp_fu_343_ce),
    .dout(grp_fu_343_p2)
);

sobel_top_icmp_64ns_64ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .OP_CODE( 0 ),
    .dout_WIDTH( 1 ))
icmp_64ns_64ns_1_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reuse_addr_reg52_fu_124),
    .din1(zext_ln19_fu_387_p1),
    .ce(grp_fu_395_ce),
    .dout(grp_fu_395_p2)
);

sobel_top_icmp_64ns_64ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .OP_CODE( 0 ),
    .dout_WIDTH( 1 ))
icmp_64ns_64ns_1_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reuse_addr_reg_fu_132),
    .din1(zext_ln19_fu_387_p1),
    .ce(grp_fu_404_ce),
    .dout(grp_fu_404_p2)
);

sobel_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter33_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter31_stage0)) begin
            ap_enable_reg_pp0_iter32 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln47_fu_326_p2 == 1'd1))) begin
            idx_fu_140 <= idx_2_fu_332_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            idx_fu_140 <= 22'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0152282_fu_164 <= 8'd0;
        end else if (((icmp_ln47_reg_842_pp0_iter30_reg == 1'd1) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
            p_0_0_0152282_fu_164 <= in_pkt_data_reg_871_pp0_iter30_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0153281_fu_152 <= 8'd0;
        end else if (((icmp_ln47_reg_842_pp0_iter30_reg == 1'd1) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
            p_0_0_0153281_fu_152 <= p_0_0_0152282_fu_164;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0154280_fu_160 <= 8'd0;
        end else if (((icmp_ln47_reg_842_pp0_iter30_reg == 1'd1) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
            p_0_0_0154280_fu_160 <= reuse_select_reg_920_pp0_iter30_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0155279_fu_148 <= 8'd0;
        end else if (((icmp_ln47_reg_842_pp0_iter30_reg == 1'd1) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
            p_0_0_0155279_fu_148 <= p_0_0_0154280_fu_160;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0156278_fu_156 <= 8'd0;
        end else if (((icmp_ln47_reg_842_pp0_iter30_reg == 1'd1) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
            p_0_0_0156278_fu_156 <= reuse_select56_fu_461_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0157277_fu_144 <= 8'd0;
        end else if (((icmp_ln47_reg_842_pp0_iter30_reg == 1'd1) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
            p_0_0_0157277_fu_144 <= p_0_0_0156278_fu_156;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg52_fu_124 <= 64'd18446744073709551615;
        end else if (((icmp_ln47_reg_842_pp0_iter26_reg == 1'd1) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
            reuse_addr_reg52_fu_124 <= zext_ln19_fu_387_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg_fu_132 <= 64'd18446744073709551615;
        end else if (((icmp_ln47_reg_842_pp0_iter26_reg == 1'd1) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
            reuse_addr_reg_fu_132 <= zext_ln19_fu_387_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg51_fu_128 <= 8'd0;
        end else if (((icmp_ln47_reg_842_pp0_iter30_reg == 1'd1) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
            reuse_reg51_fu_128 <= reuse_select_reg_920_pp0_iter30_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_136 <= 8'd0;
        end else if (((icmp_ln47_reg_842_pp0_iter28_reg == 1'd1) & (ap_enable_reg_pp0_iter29 == 1'b1))) begin
            reuse_reg_fu_136 <= in_pkt_data_reg_871_pp0_iter28_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln64_reg_937 <= add_ln64_fu_493_p2;
        addr_cmp55_reg_910 <= grp_fu_395_p2;
        addr_cmp55_reg_910_pp0_iter29_reg <= addr_cmp55_reg_910;
        addr_cmp55_reg_910_pp0_iter30_reg <= addr_cmp55_reg_910_pp0_iter29_reg;
        addr_cmp_reg_915 <= grp_fu_404_p2;
        col_reg_861 <= grp_fu_343_p2;
        icmp_ln61_1_reg_905 <= icmp_ln61_1_fu_420_p2;
        icmp_ln61_1_reg_905_pp0_iter28_reg <= icmp_ln61_1_reg_905;
        icmp_ln61_1_reg_905_pp0_iter29_reg <= icmp_ln61_1_reg_905_pp0_iter28_reg;
        icmp_ln61_1_reg_905_pp0_iter30_reg <= icmp_ln61_1_reg_905_pp0_iter29_reg;
        icmp_ln61_1_reg_905_pp0_iter31_reg <= icmp_ln61_1_reg_905_pp0_iter30_reg;
        icmp_ln61_1_reg_905_pp0_iter32_reg <= icmp_ln61_1_reg_905_pp0_iter31_reg;
        icmp_ln61_1_reg_905_pp0_iter33_reg <= icmp_ln61_1_reg_905_pp0_iter32_reg;
        icmp_ln61_reg_846_pp0_iter10_reg <= icmp_ln61_reg_846_pp0_iter9_reg;
        icmp_ln61_reg_846_pp0_iter11_reg <= icmp_ln61_reg_846_pp0_iter10_reg;
        icmp_ln61_reg_846_pp0_iter12_reg <= icmp_ln61_reg_846_pp0_iter11_reg;
        icmp_ln61_reg_846_pp0_iter13_reg <= icmp_ln61_reg_846_pp0_iter12_reg;
        icmp_ln61_reg_846_pp0_iter14_reg <= icmp_ln61_reg_846_pp0_iter13_reg;
        icmp_ln61_reg_846_pp0_iter15_reg <= icmp_ln61_reg_846_pp0_iter14_reg;
        icmp_ln61_reg_846_pp0_iter16_reg <= icmp_ln61_reg_846_pp0_iter15_reg;
        icmp_ln61_reg_846_pp0_iter17_reg <= icmp_ln61_reg_846_pp0_iter16_reg;
        icmp_ln61_reg_846_pp0_iter18_reg <= icmp_ln61_reg_846_pp0_iter17_reg;
        icmp_ln61_reg_846_pp0_iter19_reg <= icmp_ln61_reg_846_pp0_iter18_reg;
        icmp_ln61_reg_846_pp0_iter20_reg <= icmp_ln61_reg_846_pp0_iter19_reg;
        icmp_ln61_reg_846_pp0_iter21_reg <= icmp_ln61_reg_846_pp0_iter20_reg;
        icmp_ln61_reg_846_pp0_iter22_reg <= icmp_ln61_reg_846_pp0_iter21_reg;
        icmp_ln61_reg_846_pp0_iter23_reg <= icmp_ln61_reg_846_pp0_iter22_reg;
        icmp_ln61_reg_846_pp0_iter24_reg <= icmp_ln61_reg_846_pp0_iter23_reg;
        icmp_ln61_reg_846_pp0_iter25_reg <= icmp_ln61_reg_846_pp0_iter24_reg;
        icmp_ln61_reg_846_pp0_iter26_reg <= icmp_ln61_reg_846_pp0_iter25_reg;
        icmp_ln61_reg_846_pp0_iter27_reg <= icmp_ln61_reg_846_pp0_iter26_reg;
        icmp_ln61_reg_846_pp0_iter28_reg <= icmp_ln61_reg_846_pp0_iter27_reg;
        icmp_ln61_reg_846_pp0_iter29_reg <= icmp_ln61_reg_846_pp0_iter28_reg;
        icmp_ln61_reg_846_pp0_iter2_reg <= icmp_ln61_reg_846;
        icmp_ln61_reg_846_pp0_iter30_reg <= icmp_ln61_reg_846_pp0_iter29_reg;
        icmp_ln61_reg_846_pp0_iter31_reg <= icmp_ln61_reg_846_pp0_iter30_reg;
        icmp_ln61_reg_846_pp0_iter32_reg <= icmp_ln61_reg_846_pp0_iter31_reg;
        icmp_ln61_reg_846_pp0_iter33_reg <= icmp_ln61_reg_846_pp0_iter32_reg;
        icmp_ln61_reg_846_pp0_iter3_reg <= icmp_ln61_reg_846_pp0_iter2_reg;
        icmp_ln61_reg_846_pp0_iter4_reg <= icmp_ln61_reg_846_pp0_iter3_reg;
        icmp_ln61_reg_846_pp0_iter5_reg <= icmp_ln61_reg_846_pp0_iter4_reg;
        icmp_ln61_reg_846_pp0_iter6_reg <= icmp_ln61_reg_846_pp0_iter5_reg;
        icmp_ln61_reg_846_pp0_iter7_reg <= icmp_ln61_reg_846_pp0_iter6_reg;
        icmp_ln61_reg_846_pp0_iter8_reg <= icmp_ln61_reg_846_pp0_iter7_reg;
        icmp_ln61_reg_846_pp0_iter9_reg <= icmp_ln61_reg_846_pp0_iter8_reg;
        icmp_ln81_reg_851_pp0_iter10_reg <= icmp_ln81_reg_851_pp0_iter9_reg;
        icmp_ln81_reg_851_pp0_iter11_reg <= icmp_ln81_reg_851_pp0_iter10_reg;
        icmp_ln81_reg_851_pp0_iter12_reg <= icmp_ln81_reg_851_pp0_iter11_reg;
        icmp_ln81_reg_851_pp0_iter13_reg <= icmp_ln81_reg_851_pp0_iter12_reg;
        icmp_ln81_reg_851_pp0_iter14_reg <= icmp_ln81_reg_851_pp0_iter13_reg;
        icmp_ln81_reg_851_pp0_iter15_reg <= icmp_ln81_reg_851_pp0_iter14_reg;
        icmp_ln81_reg_851_pp0_iter16_reg <= icmp_ln81_reg_851_pp0_iter15_reg;
        icmp_ln81_reg_851_pp0_iter17_reg <= icmp_ln81_reg_851_pp0_iter16_reg;
        icmp_ln81_reg_851_pp0_iter18_reg <= icmp_ln81_reg_851_pp0_iter17_reg;
        icmp_ln81_reg_851_pp0_iter19_reg <= icmp_ln81_reg_851_pp0_iter18_reg;
        icmp_ln81_reg_851_pp0_iter20_reg <= icmp_ln81_reg_851_pp0_iter19_reg;
        icmp_ln81_reg_851_pp0_iter21_reg <= icmp_ln81_reg_851_pp0_iter20_reg;
        icmp_ln81_reg_851_pp0_iter22_reg <= icmp_ln81_reg_851_pp0_iter21_reg;
        icmp_ln81_reg_851_pp0_iter23_reg <= icmp_ln81_reg_851_pp0_iter22_reg;
        icmp_ln81_reg_851_pp0_iter24_reg <= icmp_ln81_reg_851_pp0_iter23_reg;
        icmp_ln81_reg_851_pp0_iter25_reg <= icmp_ln81_reg_851_pp0_iter24_reg;
        icmp_ln81_reg_851_pp0_iter26_reg <= icmp_ln81_reg_851_pp0_iter25_reg;
        icmp_ln81_reg_851_pp0_iter27_reg <= icmp_ln81_reg_851_pp0_iter26_reg;
        icmp_ln81_reg_851_pp0_iter28_reg <= icmp_ln81_reg_851_pp0_iter27_reg;
        icmp_ln81_reg_851_pp0_iter29_reg <= icmp_ln81_reg_851_pp0_iter28_reg;
        icmp_ln81_reg_851_pp0_iter2_reg <= icmp_ln81_reg_851;
        icmp_ln81_reg_851_pp0_iter30_reg <= icmp_ln81_reg_851_pp0_iter29_reg;
        icmp_ln81_reg_851_pp0_iter31_reg <= icmp_ln81_reg_851_pp0_iter30_reg;
        icmp_ln81_reg_851_pp0_iter32_reg <= icmp_ln81_reg_851_pp0_iter31_reg;
        icmp_ln81_reg_851_pp0_iter33_reg <= icmp_ln81_reg_851_pp0_iter32_reg;
        icmp_ln81_reg_851_pp0_iter3_reg <= icmp_ln81_reg_851_pp0_iter2_reg;
        icmp_ln81_reg_851_pp0_iter4_reg <= icmp_ln81_reg_851_pp0_iter3_reg;
        icmp_ln81_reg_851_pp0_iter5_reg <= icmp_ln81_reg_851_pp0_iter4_reg;
        icmp_ln81_reg_851_pp0_iter6_reg <= icmp_ln81_reg_851_pp0_iter5_reg;
        icmp_ln81_reg_851_pp0_iter7_reg <= icmp_ln81_reg_851_pp0_iter6_reg;
        icmp_ln81_reg_851_pp0_iter8_reg <= icmp_ln81_reg_851_pp0_iter7_reg;
        icmp_ln81_reg_851_pp0_iter9_reg <= icmp_ln81_reg_851_pp0_iter8_reg;
        icmp_ln84_reg_856_pp0_iter10_reg <= icmp_ln84_reg_856_pp0_iter9_reg;
        icmp_ln84_reg_856_pp0_iter11_reg <= icmp_ln84_reg_856_pp0_iter10_reg;
        icmp_ln84_reg_856_pp0_iter12_reg <= icmp_ln84_reg_856_pp0_iter11_reg;
        icmp_ln84_reg_856_pp0_iter13_reg <= icmp_ln84_reg_856_pp0_iter12_reg;
        icmp_ln84_reg_856_pp0_iter14_reg <= icmp_ln84_reg_856_pp0_iter13_reg;
        icmp_ln84_reg_856_pp0_iter15_reg <= icmp_ln84_reg_856_pp0_iter14_reg;
        icmp_ln84_reg_856_pp0_iter16_reg <= icmp_ln84_reg_856_pp0_iter15_reg;
        icmp_ln84_reg_856_pp0_iter17_reg <= icmp_ln84_reg_856_pp0_iter16_reg;
        icmp_ln84_reg_856_pp0_iter18_reg <= icmp_ln84_reg_856_pp0_iter17_reg;
        icmp_ln84_reg_856_pp0_iter19_reg <= icmp_ln84_reg_856_pp0_iter18_reg;
        icmp_ln84_reg_856_pp0_iter20_reg <= icmp_ln84_reg_856_pp0_iter19_reg;
        icmp_ln84_reg_856_pp0_iter21_reg <= icmp_ln84_reg_856_pp0_iter20_reg;
        icmp_ln84_reg_856_pp0_iter22_reg <= icmp_ln84_reg_856_pp0_iter21_reg;
        icmp_ln84_reg_856_pp0_iter23_reg <= icmp_ln84_reg_856_pp0_iter22_reg;
        icmp_ln84_reg_856_pp0_iter24_reg <= icmp_ln84_reg_856_pp0_iter23_reg;
        icmp_ln84_reg_856_pp0_iter25_reg <= icmp_ln84_reg_856_pp0_iter24_reg;
        icmp_ln84_reg_856_pp0_iter26_reg <= icmp_ln84_reg_856_pp0_iter25_reg;
        icmp_ln84_reg_856_pp0_iter27_reg <= icmp_ln84_reg_856_pp0_iter26_reg;
        icmp_ln84_reg_856_pp0_iter28_reg <= icmp_ln84_reg_856_pp0_iter27_reg;
        icmp_ln84_reg_856_pp0_iter29_reg <= icmp_ln84_reg_856_pp0_iter28_reg;
        icmp_ln84_reg_856_pp0_iter2_reg <= icmp_ln84_reg_856;
        icmp_ln84_reg_856_pp0_iter30_reg <= icmp_ln84_reg_856_pp0_iter29_reg;
        icmp_ln84_reg_856_pp0_iter31_reg <= icmp_ln84_reg_856_pp0_iter30_reg;
        icmp_ln84_reg_856_pp0_iter32_reg <= icmp_ln84_reg_856_pp0_iter31_reg;
        icmp_ln84_reg_856_pp0_iter33_reg <= icmp_ln84_reg_856_pp0_iter32_reg;
        icmp_ln84_reg_856_pp0_iter3_reg <= icmp_ln84_reg_856_pp0_iter2_reg;
        icmp_ln84_reg_856_pp0_iter4_reg <= icmp_ln84_reg_856_pp0_iter3_reg;
        icmp_ln84_reg_856_pp0_iter5_reg <= icmp_ln84_reg_856_pp0_iter4_reg;
        icmp_ln84_reg_856_pp0_iter6_reg <= icmp_ln84_reg_856_pp0_iter5_reg;
        icmp_ln84_reg_856_pp0_iter7_reg <= icmp_ln84_reg_856_pp0_iter6_reg;
        icmp_ln84_reg_856_pp0_iter8_reg <= icmp_ln84_reg_856_pp0_iter7_reg;
        icmp_ln84_reg_856_pp0_iter9_reg <= icmp_ln84_reg_856_pp0_iter8_reg;
        in_pkt_data_reg_871 <= in_stream_TDATA;
        in_pkt_data_reg_871_pp0_iter28_reg <= in_pkt_data_reg_871;
        in_pkt_data_reg_871_pp0_iter29_reg <= in_pkt_data_reg_871_pp0_iter28_reg;
        in_pkt_data_reg_871_pp0_iter30_reg <= in_pkt_data_reg_871_pp0_iter29_reg;
        in_pkt_data_reg_871_pp0_iter31_reg <= in_pkt_data_reg_871_pp0_iter30_reg;
        linebuf0_addr_reg_885 <= zext_ln19_fu_387_p1;
        linebuf0_addr_reg_885_pp0_iter28_reg <= linebuf0_addr_reg_885;
        reuse_select56_reg_927 <= reuse_select56_fu_461_p3;
        reuse_select_reg_920 <= reuse_select_fu_428_p3;
        reuse_select_reg_920_pp0_iter30_reg <= reuse_select_reg_920;
        select_ln12_1_reg_979 <= select_ln12_1_fu_676_p3;
        select_ln12_reg_974 <= select_ln12_fu_661_p3;
        sub_ln68_reg_947 <= sub_ln68_fu_513_p2;
        tmp3_reg_942 <= tmp3_fu_507_p2;
        tmp_4_reg_866 <= {{grp_fu_343_p2[11:1]}};
        tmp_5_reg_964 <= sext_ln62_fu_592_p1[32'd31];
        tmp_6_reg_969 <= sext_ln67_fu_632_p1[32'd31];
        tmp_7_reg_984 <= {{mag_fu_686_p2[10:8]}};
        tmp_reg_932 <= tmp_fu_487_p2;
        trunc_ln62_reg_952 <= trunc_ln62_fu_596_p1;
        trunc_ln67_reg_958 <= trunc_ln67_fu_636_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln47_reg_842_pp0_iter10_reg <= icmp_ln47_reg_842_pp0_iter9_reg;
        icmp_ln47_reg_842_pp0_iter11_reg <= icmp_ln47_reg_842_pp0_iter10_reg;
        icmp_ln47_reg_842_pp0_iter12_reg <= icmp_ln47_reg_842_pp0_iter11_reg;
        icmp_ln47_reg_842_pp0_iter13_reg <= icmp_ln47_reg_842_pp0_iter12_reg;
        icmp_ln47_reg_842_pp0_iter14_reg <= icmp_ln47_reg_842_pp0_iter13_reg;
        icmp_ln47_reg_842_pp0_iter15_reg <= icmp_ln47_reg_842_pp0_iter14_reg;
        icmp_ln47_reg_842_pp0_iter16_reg <= icmp_ln47_reg_842_pp0_iter15_reg;
        icmp_ln47_reg_842_pp0_iter17_reg <= icmp_ln47_reg_842_pp0_iter16_reg;
        icmp_ln47_reg_842_pp0_iter18_reg <= icmp_ln47_reg_842_pp0_iter17_reg;
        icmp_ln47_reg_842_pp0_iter19_reg <= icmp_ln47_reg_842_pp0_iter18_reg;
        icmp_ln47_reg_842_pp0_iter20_reg <= icmp_ln47_reg_842_pp0_iter19_reg;
        icmp_ln47_reg_842_pp0_iter21_reg <= icmp_ln47_reg_842_pp0_iter20_reg;
        icmp_ln47_reg_842_pp0_iter22_reg <= icmp_ln47_reg_842_pp0_iter21_reg;
        icmp_ln47_reg_842_pp0_iter23_reg <= icmp_ln47_reg_842_pp0_iter22_reg;
        icmp_ln47_reg_842_pp0_iter24_reg <= icmp_ln47_reg_842_pp0_iter23_reg;
        icmp_ln47_reg_842_pp0_iter25_reg <= icmp_ln47_reg_842_pp0_iter24_reg;
        icmp_ln47_reg_842_pp0_iter26_reg <= icmp_ln47_reg_842_pp0_iter25_reg;
        icmp_ln47_reg_842_pp0_iter27_reg <= icmp_ln47_reg_842_pp0_iter26_reg;
        icmp_ln47_reg_842_pp0_iter28_reg <= icmp_ln47_reg_842_pp0_iter27_reg;
        icmp_ln47_reg_842_pp0_iter29_reg <= icmp_ln47_reg_842_pp0_iter28_reg;
        icmp_ln47_reg_842_pp0_iter2_reg <= icmp_ln47_reg_842_pp0_iter1_reg;
        icmp_ln47_reg_842_pp0_iter30_reg <= icmp_ln47_reg_842_pp0_iter29_reg;
        icmp_ln47_reg_842_pp0_iter3_reg <= icmp_ln47_reg_842_pp0_iter2_reg;
        icmp_ln47_reg_842_pp0_iter4_reg <= icmp_ln47_reg_842_pp0_iter3_reg;
        icmp_ln47_reg_842_pp0_iter5_reg <= icmp_ln47_reg_842_pp0_iter4_reg;
        icmp_ln47_reg_842_pp0_iter6_reg <= icmp_ln47_reg_842_pp0_iter5_reg;
        icmp_ln47_reg_842_pp0_iter7_reg <= icmp_ln47_reg_842_pp0_iter6_reg;
        icmp_ln47_reg_842_pp0_iter8_reg <= icmp_ln47_reg_842_pp0_iter7_reg;
        icmp_ln47_reg_842_pp0_iter9_reg <= icmp_ln47_reg_842_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln47_reg_842 <= icmp_ln47_fu_326_p2;
        icmp_ln47_reg_842_pp0_iter1_reg <= icmp_ln47_reg_842;
        idx_1_reg_834 <= ap_sig_allocacmp_idx_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        icmp_ln61_reg_846 <= icmp_ln61_fu_358_p2;
        icmp_ln81_reg_851 <= icmp_ln81_fu_363_p2;
        icmp_ln84_reg_856 <= icmp_ln84_fu_368_p2;
        width_cast_reg_829[10 : 0] <= width_cast_fu_264_p1[10 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln47_fu_326_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln47_reg_842_pp0_iter30_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
        ap_condition_exit_pp0_iter31_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter31_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter33_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) 
    & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_idx_1 = 22'd0;
    end else begin
        ap_sig_allocacmp_idx_1 = idx_fu_140;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_343_ce = 1'b1;
    end else begin
        grp_fu_343_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_395_ce = 1'b1;
    end else begin
        grp_fu_395_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_404_ce = 1'b1;
    end else begin
        grp_fu_404_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln47_reg_842_pp0_iter26_reg == 1'd1) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln47_reg_842_pp0_iter26_reg == 1'd1) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln47_reg_842_pp0_iter28_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'd0 == addr_cmp55_reg_910) & (ap_enable_reg_pp0_iter29 == 1'b1)) | ((icmp_ln47_reg_842_pp0_iter28_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter29 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter30 == 1'b1)))) begin
        linebuf0_ce0_local = 1'b1;
    end else begin
        linebuf0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln47_reg_842_pp0_iter28_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter29 == 1'b1))) begin
        linebuf0_we0_local = 1'b1;
    end else begin
        linebuf0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter28 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln47_reg_842_pp0_iter26_reg == 1'd1) & (ap_enable_reg_pp0_iter27 == 1'b1)))) begin
        linebuf1_ce0_local = 1'b1;
    end else begin
        linebuf1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln47_reg_842_pp0_iter26_reg == 1'd1) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        linebuf1_we0_local = 1'b1;
    end else begin
        linebuf1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln64_fu_493_p2 = (zext_ln63_fu_472_p1 + zext_ln65_1_fu_483_p1);

assign add_ln65_fu_580_p2 = ($signed(sext_ln64_fu_563_p1) + $signed(linebuf0_load_cast_fu_547_p1));

assign add_ln69_1_fu_620_p2 = ($signed(add_ln69_fu_614_p2) + $signed(sext_ln69_fu_611_p1));

assign add_ln69_fu_614_p2 = ($signed(sext_ln68_fu_607_p1) + $signed(in_pkt_data_cast1_fu_550_p1));

assign add_ln71_fu_712_p2 = (select_ln12_reg_974 + select_ln12_1_reg_979);

assign and_ln61_fu_707_p2 = (xor_ln61_fu_702_p2 & icmp_ln61_1_reg_905_pp0_iter33_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001_grp1 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((1'b1 == ap_block_state28_pp0_stage0_iter27_grp1) & (ap_enable_reg_pp0_iter27 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((1'b1 == ap_block_state28_pp0_stage0_iter27_grp1) & (ap_enable_reg_pp0_iter27 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((1'b1 == ap_block_state28_pp0_stage0_iter27_grp1) & (ap_enable_reg_pp0_iter27 == 1'b1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((1'b1 == ap_block_state28_pp0_stage0_iter27_grp1) & (ap_enable_reg_pp0_iter27 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((1'b1 == ap_block_state28_pp0_stage0_iter27_grp1) & (ap_enable_reg_pp0_iter27 == 1'b1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state28_pp0_stage0_iter27_grp1 = ((icmp_ln47_reg_842_pp0_iter26_reg == 1'd1) & (in_stream_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_343_p1 = width_cast_reg_829;

assign gx_fu_586_p2 = ($signed(add_ln65_fu_580_p2) + $signed(sext_ln65_fu_576_p1));

assign gy_fu_626_p2 = (add_ln69_1_fu_620_p2 - linebuf0_load_cast_fu_547_p1);

assign icmp_ln47_fu_326_p2 = ((ap_sig_allocacmp_idx_1 < total) ? 1'b1 : 1'b0);

assign icmp_ln61_1_fu_420_p2 = (($signed(tmp_4_reg_866) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_358_p2 = ((idx_1_reg_834 < zext_ln61_fu_354_p1) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_716_p2 = ((tmp_7_reg_984 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_363_p2 = ((idx_1_reg_834 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_368_p2 = ((idx_1_reg_834 == add_ln84) ? 1'b1 : 1'b0);

assign idx_2_fu_332_p2 = (ap_sig_allocacmp_idx_1 + 22'd1);

assign in_pkt_data_cast1_fu_550_p1 = in_pkt_data_reg_871_pp0_iter31_reg;

assign in_pkt_data_cast_fu_553_p1 = in_pkt_data_reg_871_pp0_iter31_reg;

assign linebuf0_address0 = linebuf0_addr_reg_885_pp0_iter28_reg;

assign linebuf0_ce0 = linebuf0_ce0_local;

assign linebuf0_d0 = reuse_select_fu_428_p3;

assign linebuf0_load_cast_fu_547_p1 = reuse_select56_reg_927;

assign linebuf0_we0 = linebuf0_we0_local;

assign linebuf1_address0 = zext_ln19_fu_387_p1;

assign linebuf1_ce0 = linebuf1_ce0_local;

assign linebuf1_d0 = in_stream_TDATA;

assign linebuf1_we0 = linebuf1_we0_local;

assign mag_fu_686_p2 = (zext_ln10_fu_667_p1 + zext_ln71_fu_682_p1);

assign out_pix_fu_725_p3 = ((icmp_ln6_fu_716_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln7_fu_721_p1);

assign out_stream_TDATA = ((and_ln61_fu_707_p2[0:0] == 1'b1) ? out_pix_fu_725_p3 : 8'd0);

assign out_stream_TDEST = 1'd0;

assign out_stream_TID = 1'd0;

assign out_stream_TKEEP = 1'd1;

assign out_stream_TLAST = icmp_ln84_reg_856_pp0_iter33_reg;

assign out_stream_TSTRB = 1'd1;

assign out_stream_TUSER = icmp_ln81_reg_851_pp0_iter33_reg;

assign p2y_fu_347_p3 = {{empty}, {1'd0}};

assign p_0_0_0152282_cast_fu_503_p1 = p_0_0_0152282_fu_164;

assign p_0_0_0155279_cast_fu_476_p1 = p_0_0_0155279_fu_148;

assign p_0_0_0156278_cast_fu_499_p1 = p_0_0_0156278_fu_156;

assign reuse_select56_fu_461_p3 = ((addr_cmp55_reg_910_pp0_iter30_reg[0:0] == 1'b1) ? reuse_reg51_fu_128 : linebuf0_q0);

assign reuse_select_fu_428_p3 = ((addr_cmp_reg_915[0:0] == 1'b1) ? reuse_reg_fu_136 : linebuf1_q0);

assign select_ln12_1_fu_676_p3 = ((tmp_6_reg_969[0:0] == 1'b1) ? sub_ln12_1_fu_671_p2 : trunc_ln67_reg_958);

assign select_ln12_fu_661_p3 = ((tmp_5_reg_964[0:0] == 1'b1) ? sub_ln12_fu_656_p2 : trunc_ln62_reg_952);

assign sext_ln62_fu_592_p1 = gx_fu_586_p2;

assign sext_ln64_fu_563_p1 = $signed(tmp_1_fu_556_p3);

assign sext_ln65_fu_576_p1 = $signed(sub_ln64_fu_570_p2);

assign sext_ln67_fu_632_p1 = gy_fu_626_p2;

assign sext_ln68_fu_607_p1 = $signed(tmp_2_fu_600_p3);

assign sext_ln69_fu_611_p1 = $signed(sub_ln68_reg_947);

assign sub_ln12_1_fu_671_p2 = (10'd0 - trunc_ln67_reg_958);

assign sub_ln12_fu_656_p2 = (10'd0 - trunc_ln62_reg_952);

assign sub_ln64_fu_570_p2 = (in_pkt_data_cast_fu_553_p1 - zext_ln64_fu_567_p1);

assign sub_ln68_fu_513_p2 = (zext_ln65_1_fu_483_p1 - zext_ln63_fu_472_p1);

assign tmp3_fu_507_p2 = (p_0_0_0152282_cast_fu_503_p1 - p_0_0_0156278_cast_fu_499_p1);

assign tmp_1_fu_556_p3 = {{tmp_reg_932}, {1'd0}};

assign tmp_2_fu_600_p3 = {{tmp3_reg_942}, {1'd0}};

assign tmp_fu_487_p2 = (zext_ln65_fu_480_p1 - p_0_0_0155279_cast_fu_476_p1);

assign trunc_ln62_fu_596_p1 = gx_fu_586_p2[9:0];

assign trunc_ln67_fu_636_p1 = gy_fu_626_p2[9:0];

assign trunc_ln7_fu_721_p1 = add_ln71_fu_712_p2[7:0];

assign width_cast_fu_264_p1 = width;

assign xor_ln61_fu_702_p2 = (icmp_ln61_reg_846_pp0_iter33_reg ^ 1'd1);

assign zext_ln10_fu_667_p1 = select_ln12_fu_661_p3;

assign zext_ln19_fu_387_p1 = col_reg_861;

assign zext_ln61_fu_354_p1 = p2y_fu_347_p3;

assign zext_ln63_fu_472_p1 = p_0_0_0157277_fu_144;

assign zext_ln64_fu_567_p1 = add_ln64_reg_937;

assign zext_ln65_1_fu_483_p1 = p_0_0_0153281_fu_152;

assign zext_ln65_fu_480_p1 = reuse_select_reg_920_pp0_iter30_reg;

assign zext_ln71_fu_682_p1 = select_ln12_1_fu_676_p3;

always @ (posedge ap_clk) begin
    width_cast_reg_829[21:11] <= 11'b00000000000;
end

endmodule //sobel_top_sobel_core_Pipeline_VITIS_LOOP_47_4
