// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module sobel_top_sobel_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        width,
        height
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input  [31:0] width;
input  [31:0] height;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_stream_TREADY;
reg[7:0] out_stream_TDATA;
reg[0:0] out_stream_TKEEP;
reg[0:0] out_stream_TSTRB;
reg[0:0] out_stream_TUSER;
reg[0:0] out_stream_TLAST;
reg[0:0] out_stream_TID;
reg[0:0] out_stream_TDEST;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [10:0] empty_fu_140_p1;
reg   [10:0] empty_reg_208;
wire   [10:0] empty_18_fu_144_p1;
reg   [10:0] empty_18_reg_217;
wire   [0:0] or_ln19_fu_160_p2;
reg   [0:0] or_ln19_reg_223;
wire   [0:0] or_ln20_fu_178_p2;
reg   [0:0] or_ln20_reg_227;
wire   [21:0] mul_ln95_fu_190_p2;
reg   [21:0] mul_ln95_reg_231;
wire    ap_CS_fsm_state3;
wire   [10:0] add_ln95_fu_196_p2;
reg   [10:0] add_ln95_reg_236;
wire    ap_CS_fsm_state4;
wire   [10:0] add_ln51_fu_202_p2;
reg   [10:0] add_ln51_reg_241;
reg    linebuf0_ce0;
wire   [7:0] linebuf0_q0;
reg   [10:0] linebuf0_address1;
reg    linebuf0_ce1;
reg    linebuf0_we1;
reg   [7:0] linebuf0_d1;
reg   [10:0] linebuf1_address1;
reg    linebuf1_ce1;
reg    linebuf1_we1;
reg   [7:0] linebuf1_d1;
wire   [7:0] linebuf1_q1;
wire    grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start;
wire    grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_done;
wire    grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_idle;
wire    grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_ready;
wire   [10:0] grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_address1;
wire    grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_ce1;
wire    grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_we1;
wire   [7:0] grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_d1;
wire   [10:0] grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_address1;
wire    grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_ce1;
wire    grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_we1;
wire   [7:0] grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_d1;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_done;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_idle;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_ready;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TREADY;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_in_stream_TREADY;
wire   [10:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_address0;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_ce0;
wire   [10:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_address1;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_ce1;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_we1;
wire   [7:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_d1;
wire   [10:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_address1;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_ce1;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_we1;
wire   [7:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_d1;
wire   [7:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TDATA;
wire    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID;
wire   [0:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TKEEP;
wire   [0:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TSTRB;
wire   [0:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TUSER;
wire   [0:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TLAST;
wire   [0:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TID;
wire   [0:0] grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TDEST;
reg    grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [7:0] out_stream_TDATA_reg;
reg   [0:0] out_stream_TKEEP_reg;
reg   [0:0] out_stream_TSTRB_reg;
reg   [0:0] out_stream_TUSER_reg;
reg   [0:0] out_stream_TLAST_reg;
reg   [0:0] out_stream_TID_reg;
reg   [0:0] out_stream_TDEST_reg;
wire   [0:0] icmp_ln19_fu_148_p2;
wire   [0:0] icmp_ln19_1_fu_154_p2;
wire   [0:0] icmp_ln20_fu_166_p2;
wire   [0:0] icmp_ln20_1_fu_172_p2;
wire   [10:0] mul_ln95_fu_190_p0;
wire   [10:0] mul_ln95_fu_190_p1;
reg    ap_predicate_op34_call_state5;
reg    ap_block_state5_on_subcall_done;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire   [21:0] mul_ln95_fu_190_p00;
wire   [21:0] mul_ln95_fu_190_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start_reg = 1'b0;
#0 grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start_reg = 1'b0;
end

sobel_top_sobel_core_linebuf0_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_address0),
    .ce0(linebuf0_ce0),
    .q0(linebuf0_q0),
    .address1(linebuf0_address1),
    .ce1(linebuf0_ce1),
    .we1(linebuf0_we1),
    .d1(linebuf0_d1)
);

sobel_top_sobel_core_linebuf1_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address1(linebuf1_address1),
    .ce1(linebuf1_ce1),
    .we1(linebuf1_we1),
    .d1(linebuf1_d1),
    .q1(linebuf1_q1)
);

sobel_top_sobel_core_Pipeline_init_linebuf grp_sobel_core_Pipeline_init_linebuf_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start),
    .ap_done(grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_done),
    .ap_idle(grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_idle),
    .ap_ready(grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_ready),
    .empty(empty_reg_208),
    .linebuf0_address1(grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_address1),
    .linebuf0_ce1(grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_ce1),
    .linebuf0_we1(grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_we1),
    .linebuf0_d1(grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_d1),
    .linebuf1_address1(grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_address1),
    .linebuf1_ce1(grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_ce1),
    .linebuf1_we1(grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_we1),
    .linebuf1_d1(grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_d1)
);

sobel_top_sobel_core_Pipeline_row_loop_col_loop grp_sobel_core_Pipeline_row_loop_col_loop_fu_101(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start),
    .ap_done(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_done),
    .ap_idle(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_idle),
    .ap_ready(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_ready),
    .in_stream_TVALID(in_stream_TVALID),
    .out_stream_TREADY(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TREADY),
    .width(empty_reg_208),
    .mul_ln95(mul_ln95_reg_231),
    .zext_ln53_1(empty_reg_208),
    .add_ln95(add_ln95_reg_236),
    .in_stream_TDATA(in_stream_TDATA),
    .in_stream_TREADY(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP),
    .in_stream_TSTRB(in_stream_TSTRB),
    .in_stream_TUSER(in_stream_TUSER),
    .in_stream_TLAST(in_stream_TLAST),
    .in_stream_TID(in_stream_TID),
    .in_stream_TDEST(in_stream_TDEST),
    .linebuf0_address0(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_address0),
    .linebuf0_ce0(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_ce0),
    .linebuf0_q0(linebuf0_q0),
    .linebuf0_address1(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_address1),
    .linebuf0_ce1(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_ce1),
    .linebuf0_we1(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_we1),
    .linebuf0_d1(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_d1),
    .linebuf1_address1(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_address1),
    .linebuf1_ce1(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_ce1),
    .linebuf1_we1(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_we1),
    .linebuf1_d1(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_d1),
    .linebuf1_q1(linebuf1_q1),
    .add_ln51(add_ln51_reg_241),
    .out_stream_TDATA(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TDATA),
    .out_stream_TVALID(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID),
    .out_stream_TKEEP(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TKEEP),
    .out_stream_TSTRB(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TSTRB),
    .out_stream_TUSER(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TUSER),
    .out_stream_TLAST(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TLAST),
    .out_stream_TID(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TID),
    .out_stream_TDEST(grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TDEST)
);

sobel_top_mul_11ns_11ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 22 ))
mul_11ns_11ns_22_1_1_U25(
    .din0(mul_ln95_fu_190_p0),
    .din1(mul_ln95_fu_190_p1),
    .dout(mul_ln95_fu_190_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_ready == 1'b1)) begin
            grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_ready == 1'b1)) begin
            grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln51_reg_241 <= add_ln51_fu_202_p2;
        add_ln95_reg_236 <= add_ln95_fu_196_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_18_reg_217 <= empty_18_fu_144_p1;
        empty_reg_208 <= empty_fu_140_p1;
        or_ln19_reg_223 <= or_ln19_fu_160_p2;
        or_ln20_reg_227 <= or_ln20_fu_178_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln95_reg_231 <= mul_ln95_fu_190_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TDATA_reg <= grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TDATA;
        out_stream_TDEST_reg <= grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TDEST;
        out_stream_TID_reg <= grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TID;
        out_stream_TKEEP_reg <= grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TKEEP;
        out_stream_TLAST_reg <= grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TLAST;
        out_stream_TSTRB_reg <= grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TSTRB;
        out_stream_TUSER_reg <= grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TUSER;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        in_stream_TREADY = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_in_stream_TREADY;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf0_address1 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf0_address1 = grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_address1;
    end else begin
        linebuf0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf0_ce0 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_ce0;
    end else begin
        linebuf0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf0_ce1 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf0_ce1 = grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_ce1;
    end else begin
        linebuf0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf0_d1 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf0_d1 = grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_d1;
    end else begin
        linebuf0_d1 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf0_we1 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf0_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf0_we1 = grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf0_we1;
    end else begin
        linebuf0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf1_address1 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf1_address1 = grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_address1;
    end else begin
        linebuf1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf1_ce1 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf1_ce1 = grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_ce1;
    end else begin
        linebuf1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf1_d1 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf1_d1 = grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_d1;
    end else begin
        linebuf1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linebuf1_we1 = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_linebuf1_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf1_we1 = grp_sobel_core_Pipeline_init_linebuf_fu_94_linebuf1_we1;
    end else begin
        linebuf1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TDATA = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TDATA;
    end else begin
        out_stream_TDATA = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TDEST = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TDEST;
    end else begin
        out_stream_TDEST = out_stream_TDEST_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TID = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TID;
    end else begin
        out_stream_TID = out_stream_TID_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TKEEP = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TKEEP;
    end else begin
        out_stream_TKEEP = out_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TLAST = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TLAST;
    end else begin
        out_stream_TLAST = out_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TSTRB = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TSTRB;
    end else begin
        out_stream_TSTRB = out_stream_TSTRB_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TUSER = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TUSER;
    end else begin
        out_stream_TUSER = out_stream_TUSER_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((or_ln20_fu_178_p2 == 1'd0) & (or_ln19_fu_160_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((or_ln20_fu_178_p2 == 1'd1) | (or_ln19_fu_160_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_fu_202_p2 = ($signed(empty_reg_208) + $signed(11'd2047));

assign add_ln95_fu_196_p2 = ($signed(empty_18_reg_217) + $signed(11'd2047));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state5_on_subcall_done = ((ap_predicate_op34_call_state5 == 1'b1) & (grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op34_call_state5 = ((or_ln20_reg_227 == 1'd0) & (or_ln19_reg_223 == 1'd0));
end

assign empty_18_fu_144_p1 = height[10:0];

assign empty_fu_140_p1 = width[10:0];

assign grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start = grp_sobel_core_Pipeline_init_linebuf_fu_94_ap_start_reg;

assign grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_ap_start_reg;

assign grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TREADY = (out_stream_TREADY & ap_CS_fsm_state5);

assign icmp_ln19_1_fu_154_p2 = (($signed(height) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_148_p2 = (($signed(width) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln20_1_fu_172_p2 = (($signed(height) > $signed(32'd1920)) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_166_p2 = (($signed(width) > $signed(32'd1920)) ? 1'b1 : 1'b0);

assign mul_ln95_fu_190_p0 = mul_ln95_fu_190_p00;

assign mul_ln95_fu_190_p00 = empty_18_reg_217;

assign mul_ln95_fu_190_p1 = mul_ln95_fu_190_p10;

assign mul_ln95_fu_190_p10 = empty_reg_208;

assign or_ln19_fu_160_p2 = (icmp_ln19_fu_148_p2 | icmp_ln19_1_fu_154_p2);

assign or_ln20_fu_178_p2 = (icmp_ln20_fu_166_p2 | icmp_ln20_1_fu_172_p2);

assign out_stream_TVALID = grp_sobel_core_Pipeline_row_loop_col_loop_fu_101_out_stream_TVALID;

endmodule //sobel_top_sobel_core
