// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module sobel_top_sobel_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        width,
        height
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input  [31:0] width;
input  [31:0] height;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_stream_TREADY;
reg[7:0] out_stream_TDATA;
reg[0:0] out_stream_TKEEP;
reg[0:0] out_stream_TSTRB;
reg[0:0] out_stream_TUSER;
reg[0:0] out_stream_TLAST;
reg[0:0] out_stream_TID;
reg[0:0] out_stream_TDEST;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [10:0] empty_fu_143_p1;
reg   [10:0] empty_reg_198;
wire   [0:0] icmp_ln19_fu_147_p2;
reg   [0:0] icmp_ln19_reg_205;
wire   [0:0] icmp_ln19_1_fu_153_p2;
reg   [0:0] icmp_ln19_1_reg_210;
wire   [0:0] or_ln19_fu_159_p2;
reg   [0:0] or_ln19_reg_215;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln20_fu_163_p2;
reg   [0:0] icmp_ln20_reg_219;
wire   [0:0] icmp_ln20_1_fu_168_p2;
reg   [0:0] icmp_ln20_1_reg_224;
wire   [0:0] or_ln20_fu_173_p2;
reg   [0:0] or_ln20_reg_229;
wire    ap_CS_fsm_state3;
wire   [21:0] trunc_ln45_fu_177_p1;
reg   [21:0] trunc_ln45_reg_233;
wire    ap_CS_fsm_state7;
wire   [21:0] add_ln84_fu_181_p2;
reg   [21:0] add_ln84_reg_239;
wire    ap_CS_fsm_state8;
reg   [10:0] linebuf0_address0;
reg    linebuf0_ce0;
reg    linebuf0_we0;
reg   [7:0] linebuf0_d0;
wire   [7:0] linebuf0_q0;
reg   [10:0] linebuf1_address0;
reg    linebuf1_ce0;
reg    linebuf1_we0;
reg   [7:0] linebuf1_d0;
wire   [7:0] linebuf1_q0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_done;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_idle;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_ready;
wire   [10:0] grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_address0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_ce0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_we0;
wire   [7:0] grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_d0;
wire   [10:0] grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_address0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_ce0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_we0;
wire   [7:0] grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_d0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_done;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_idle;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_ready;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TREADY;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_in_stream_TREADY;
wire   [10:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_address0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_ce0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_we0;
wire   [7:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_d0;
wire   [10:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_address0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_ce0;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_we0;
wire   [7:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_d0;
wire   [7:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TDATA;
wire    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID;
wire   [0:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TKEEP;
wire   [0:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TSTRB;
wire   [0:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TUSER;
wire   [0:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TLAST;
wire   [0:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TID;
wire   [0:0] grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TDEST;
reg    grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [7:0] out_stream_TDATA_reg;
reg   [0:0] out_stream_TKEEP_reg;
reg   [0:0] out_stream_TSTRB_reg;
reg   [0:0] out_stream_TUSER_reg;
reg   [0:0] out_stream_TLAST_reg;
reg   [0:0] out_stream_TID_reg;
reg   [0:0] out_stream_TDEST_reg;
wire  signed [31:0] empty_fu_143_p0;
wire  signed [31:0] icmp_ln19_fu_147_p0;
wire  signed [31:0] icmp_ln19_1_fu_153_p0;
wire  signed [31:0] icmp_ln20_fu_163_p0;
wire  signed [31:0] icmp_ln20_1_fu_168_p0;
wire   [31:0] grp_fu_139_p2;
reg    grp_fu_139_ce;
wire    ap_CS_fsm_state6;
reg    ap_predicate_op40_call_state10;
reg    ap_block_state10_on_subcall_done;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start_reg = 1'b0;
#0 grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start_reg = 1'b0;
end

sobel_top_sobel_core_linebuf0_RAM_1P_BRAM_2R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf0_address0),
    .ce0(linebuf0_ce0),
    .we0(linebuf0_we0),
    .d0(linebuf0_d0),
    .q0(linebuf0_q0)
);

sobel_top_sobel_core_linebuf0_RAM_1P_BRAM_2R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf1_address0),
    .ce0(linebuf1_ce0),
    .we0(linebuf1_we0),
    .d0(linebuf1_d0),
    .q0(linebuf1_q0)
);

sobel_top_sobel_core_Pipeline_VITIS_LOOP_31_1 grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start),
    .ap_done(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_done),
    .ap_idle(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_idle),
    .ap_ready(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_ready),
    .empty(empty_reg_198),
    .linebuf0_address0(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_address0),
    .linebuf0_ce0(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_ce0),
    .linebuf0_we0(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_we0),
    .linebuf0_d0(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_d0),
    .linebuf1_address0(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_address0),
    .linebuf1_ce0(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_ce0),
    .linebuf1_we0(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_we0),
    .linebuf1_d0(grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_d0)
);

sobel_top_sobel_core_Pipeline_VITIS_LOOP_47_4 grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start),
    .ap_done(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_done),
    .ap_idle(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_idle),
    .ap_ready(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_ready),
    .in_stream_TVALID(in_stream_TVALID),
    .out_stream_TREADY(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TREADY),
    .total(trunc_ln45_reg_233),
    .width(empty_reg_198),
    .in_stream_TDATA(in_stream_TDATA),
    .in_stream_TREADY(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP),
    .in_stream_TSTRB(in_stream_TSTRB),
    .in_stream_TUSER(in_stream_TUSER),
    .in_stream_TLAST(in_stream_TLAST),
    .in_stream_TID(in_stream_TID),
    .in_stream_TDEST(in_stream_TDEST),
    .linebuf0_address0(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_address0),
    .linebuf0_ce0(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_ce0),
    .linebuf0_we0(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_we0),
    .linebuf0_d0(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_d0),
    .linebuf0_q0(linebuf0_q0),
    .linebuf1_address0(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_address0),
    .linebuf1_ce0(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_ce0),
    .linebuf1_we0(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_we0),
    .linebuf1_d0(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_d0),
    .linebuf1_q0(linebuf1_q0),
    .empty(empty_reg_198),
    .add_ln84(add_ln84_reg_239),
    .out_stream_TDATA(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TDATA),
    .out_stream_TVALID(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID),
    .out_stream_TKEEP(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TKEEP),
    .out_stream_TSTRB(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TSTRB),
    .out_stream_TUSER(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TUSER),
    .out_stream_TLAST(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TLAST),
    .out_stream_TID(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TID),
    .out_stream_TDEST(grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TDEST)
);

sobel_top_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(height),
    .din1(width),
    .ce(grp_fu_139_ce),
    .dout(grp_fu_139_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_ready == 1'b1)) begin
            grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_ready == 1'b1)) begin
            grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln84_reg_239 <= add_ln84_fu_181_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_198 <= empty_fu_143_p1;
        icmp_ln19_1_reg_210 <= icmp_ln19_1_fu_153_p2;
        icmp_ln19_reg_205 <= icmp_ln19_fu_147_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln20_1_reg_224 <= icmp_ln20_1_fu_168_p2;
        icmp_ln20_reg_219 <= icmp_ln20_fu_163_p2;
        or_ln19_reg_215 <= or_ln19_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        or_ln20_reg_229 <= or_ln20_fu_173_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TDATA_reg <= grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TDATA;
        out_stream_TDEST_reg <= grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TDEST;
        out_stream_TID_reg <= grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TID;
        out_stream_TKEEP_reg <= grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TKEEP;
        out_stream_TLAST_reg <= grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TLAST;
        out_stream_TSTRB_reg <= grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TSTRB;
        out_stream_TUSER_reg <= grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        trunc_ln45_reg_233 <= trunc_ln45_fu_177_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_done == 1'b1)))) begin
        grp_fu_139_ce = 1'b1;
    end else begin
        grp_fu_139_ce = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        in_stream_TREADY = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_in_stream_TREADY;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        linebuf0_address0 = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf0_address0 = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_address0;
    end else begin
        linebuf0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        linebuf0_ce0 = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf0_ce0 = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_ce0;
    end else begin
        linebuf0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        linebuf0_d0 = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf0_d0 = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_d0;
    end else begin
        linebuf0_d0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        linebuf0_we0 = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf0_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf0_we0 = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf0_we0;
    end else begin
        linebuf0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        linebuf1_address0 = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf1_address0 = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_address0;
    end else begin
        linebuf1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        linebuf1_ce0 = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf1_ce0 = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_ce0;
    end else begin
        linebuf1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        linebuf1_d0 = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf1_d0 = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_d0;
    end else begin
        linebuf1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        linebuf1_we0 = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_linebuf1_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf1_we0 = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_linebuf1_we0;
    end else begin
        linebuf1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TDATA = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TDATA;
    end else begin
        out_stream_TDATA = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TDEST = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TDEST;
    end else begin
        out_stream_TDEST = out_stream_TDEST_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TID = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TID;
    end else begin
        out_stream_TID = out_stream_TID_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TKEEP = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TKEEP;
    end else begin
        out_stream_TKEEP = out_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TLAST = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TLAST;
    end else begin
        out_stream_TLAST = out_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TSTRB = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TSTRB;
    end else begin
        out_stream_TSTRB = out_stream_TSTRB_reg;
    end
end

always @ (*) begin
    if (((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID == 1'b1))) begin
        out_stream_TUSER = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TUSER;
    end else begin
        out_stream_TUSER = out_stream_TUSER_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((or_ln19_fu_159_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((or_ln20_fu_173_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln84_fu_181_p2 = ($signed(trunc_ln45_reg_233) + $signed(22'd4194303));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((ap_predicate_op40_call_state10 == 1'b1) & (grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op40_call_state10 = ((or_ln20_reg_229 == 1'd0) & (or_ln19_reg_215 == 1'd0));
end

assign empty_fu_143_p0 = width;

assign empty_fu_143_p1 = empty_fu_143_p0[10:0];

assign grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start = grp_sobel_core_Pipeline_VITIS_LOOP_31_1_fu_94_ap_start_reg;

assign grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_ap_start_reg;

assign grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TREADY = (out_stream_TREADY & ap_CS_fsm_state10);

assign icmp_ln19_1_fu_153_p0 = height;

assign icmp_ln19_1_fu_153_p2 = (($signed(icmp_ln19_1_fu_153_p0) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_147_p0 = width;

assign icmp_ln19_fu_147_p2 = (($signed(icmp_ln19_fu_147_p0) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln20_1_fu_168_p0 = height;

assign icmp_ln20_1_fu_168_p2 = (($signed(icmp_ln20_1_fu_168_p0) > $signed(32'd1920)) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_163_p0 = width;

assign icmp_ln20_fu_163_p2 = (($signed(icmp_ln20_fu_163_p0) > $signed(32'd1920)) ? 1'b1 : 1'b0);

assign or_ln19_fu_159_p2 = (icmp_ln19_reg_205 | icmp_ln19_1_reg_210);

assign or_ln20_fu_173_p2 = (icmp_ln20_reg_219 | icmp_ln20_1_reg_224);

assign out_stream_TVALID = grp_sobel_core_Pipeline_VITIS_LOOP_47_4_fu_101_out_stream_TVALID;

assign trunc_ln45_fu_177_p1 = grp_fu_139_p2[21:0];

endmodule //sobel_top_sobel_core
